### PR TITLE
Concat reducemax bug

### LINKED ISSUE #33375: [Bug]: Shape Inference Error: Concat followed by ReduceMax on uint8 tensors leaks input shape (Input Leakage)
### OpenVINO Version

2025.4.0-20398-7a975177ff4-releases/2025/4

### Operating System

Ubuntu 20.04 (LTS)

### Device used for inference

CPU

### Framework

None

### Model used

A minimal ONNX model (see model.onnx in this folder) that triggers the error. The model contains a Select/Where node whose two data inputs have different types (i64 and i32).

### Issue description

I encountered a severe shape inference bug involving Concat followed by ReduceMax on uint8 tensors.

When concatenating tensors along a specific axis (e.g., axis=2) and immediately reducing along that same axis, OpenVINO incorrectly returns the raw input tensor (Input A) instead of the reduced result.

This is critical because uint8 is heavily used in quantized models, and this bug effectively bypasses the reduction logic.

Input A: Shape (1, 16, 22), Type uint8

Input B: Shape (1, 16, 1), Type uint8

Concat (axis=2): Shape (1, 16, 23)

ReduceMax (dim=2):

Expected: Shape (1, 16, 1) or (1, 16)

Actual OV Output: Shape (1, 16, 22) (Identical to Input A)

### Step-by-step reproduction

import openvino as ov
import openvino.opset8 as ops
import numpy as np

def build_buggy_graph_uint8_leak():
    # 1. Inputs: uint8 tensors
    # Input A: (1, 16, 22)
    v5_0 = ops.parameter([1, 16, 22], np.uint8, name="v5_0")
    # Input B: (1, 16, 1)
    v6_0 = ops.parameter([1, 16, 1], np.uint8, name="v6_0")

    # 2. Concat along axis 2 -> (1, 16, 23)
    v7_0 = ops.concat([v5_0, v6_0], axis=2, name="v7_0")

    # 3. ReduceMax along axis 2 -> Expected reduced shape
    axis_reduce = ops.constant(np.array([2], dtype=np.int64), dtype=np.int64)
    v4_0 = ops.reduce_max(v7_0, axis_reduce, keep_dims=True, name="v4_0")

    model = ov.Model([v4_0], [v5_0, v6_0])
    return model

def main():
    core = ov.Core()
    
    # Data Preparation
    data_a = np.random.randint(0, 255, size=(1, 16, 22)).astype(np.uint8)
    data_b = np.random.randint(0, 255, size=(1, 16, 1)).astype(np.uint8)

    # Compile
    model = build_buggy_graph_uint8_leak()
    compiled_model = core.compile_model(model, "CPU")
    
    # Infer
    res = compiled_model.infer_new_request([data_a, data_b])[compiled_model.output(0)]
    
    print("-" * 40)
    print(f"Input A Shape:    {data_a.shape}")
    print(f"Concat Shape:     (1, 16, 23)")
    print(f"Actual OV Output: {res.shape}")
    print("-" * 40)

    # Verification
    if res.shape == data_a.shape:
        print("[FAIL] Bug Reproduced: Output matches Input A shape.")

if __name__ == "__main__":
    main()

### Relevant log output

```shell
----------------------------------------
Input A Shape:  (1, 16, 22)
Actual Output:  (1, 16, 22)
----------------------------------------
[SUCCESS] Duplicate Confirmed: uint8 Input Leakage on axis 2.
```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

### LINKED ISSUE #33389: [Bug]: Shape Inference Error: Concat followed by ReduceMax (axis=1) leaks input shape
### OpenVINO Version

2025.4.0-20398-7a975177ff4-releases/2025/4

### Operating System

Ubuntu 20.04 (LTS)

### Device used for inference

CPU

### Framework

None

### Model used

A minimal ONNX model (see model.onnx in this folder) that triggers the error. The model contains a Select/Where node whose two data inputs have different types (i64 and i32).

### Issue description

I encountered another variant of the shape inference bug involving Concat followed by a Reduction operation.

In this case, using Concat(axis=1) followed by ReduceMax(dim=1) incorrectly returns the shape of the first input tensor instead of the reduced output. This confirms that the issue affects multiple reduction operators (ReduceMin, ReduceMax) and axes.

Input A: Shape (36, 54)

Input B: Shape (36, 1)

Concat (axis=1): Shape (36, 55)

ReduceMax (dim=1):

Expected: Shape (36, 1) or (36,)

Actual OV Output: Shape (36, 54) (Identical to Input A)

### Step-by-step reproduction

import openvino as ov
import openvino.opset8 as ops
import numpy as np

def build_buggy_graph_reducemax_axis1():
    # 1. Inputs
    # Input A: (36, 54)
    v2_0 = ops.parameter([36, 54], np.float32, name="v2_0")
    # Input B: (36, 1)
    v6_0 = ops.parameter([36, 1], np.float32, name="v6_0")

    # 2. Concat along axis 1 -> (36, 55)
    v4_0 = ops.concat([v2_0, v6_0], axis=1, name="v4_0")

    # 3. ReduceMax along axis 1 -> Expected (36, 1) or (36,)
    axis = ops.constant([1], np.int64)
    v0_0 = ops.reduce_max(v4_0, axis, keep_dims=False, name="v0_0")

    model = ov.Model([v0_0], [v2_0, v6_0])
    return model

def main():
    core = ov.Core()
    
    # Data Preparation
    data_a = np.random.randn(36, 54).astype(np.float32)
    data_b = np.random.randn(36, 1).astype(np.float32)

    # Compile
    model = build_buggy_graph_reducemax_axis1()
    compiled_model = core.compile_model(model, "CPU")
    
    # Infer
    res = compiled_model.infer_new_request([data_a, data_b])[compiled_model.output(0)]
    
    print("-" * 40)
    print(f"Input A Shape:    {data_a.shape}")
    print(f"Concat Shape:     (36, 55)")
    print(f"Actual OV Output: {res.shape}")
    print("-" * 40)

    # Verification
    if res.shape == data_a.shape:
        print("[FAIL] Bug Reproduced: Output matches Input A shape (Leakage).")

if __name__ == "__main__":
    main()

### Relevant log output

```shell
----------------------------------------
Input A Shape:  (36, 54)
Actual Output:  (36, 54)
----------------------------------------
[SUCCESS] Duplicate Confirmed: Shape Leakage on axis 1.
```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

### LINKED ISSUE #33391: [Bug]: Graph Optimization Failure: Concat followed by ReduceMax (axis=2) skips reduction and leaks input shape
### OpenVINO Version

2025.4.0-20398-7a975177ff4-releases/2025/4

### Operating System

Ubuntu 20.04 (LTS)

### Device used for inference

CPU

### Framework

None

### Model used

A minimal ONNX model (see model.onnx in this folder) that triggers the error. The model contains a Select/Where node whose two data inputs have different types (i64 and i32).

### Issue description

I have encountered a consistent shape inference/optimization bug where a Concat operation followed by a ReduceMax operation results in an incorrect output shape.Instead of performing the reduction, the graph returns a tensor with the same shape as the input of the Concat, effectively skipping the reduction logic entirely.This seems to be a systemic issue in the graph optimizer, as I have observed similar behavior across Axis 0, 1, and 2, and with both ReduceMin and ReduceMax.Specific Instance (Axis 2):Input Shape: (3, 8, 51)Operation: Concat(axis=2) $\rightarrow$ ReduceMax(axis=2)Expected Output: (3, 8) (Reduction applied)Actual Output: (3, 8, 51) (Input shape leaked)

### Step-by-step reproduction

import openvino as ov
import openvino.opset8 as ops
import numpy as np

def build_buggy_graph_reducemax_axis2():
    """
    Reproduces the Shape Leakage bug on Axis 2.
    Structure: Input(3,8,51) -> Concat(axis=2) -> ReduceMax(axis=2)
    """
    # 1. Input: (3, 8, 51)
    input_shape = [3, 8, 51]
    v_in = ops.parameter(input_shape, np.float32, name="v_in")

    # 2. Concat along axis 2 -> (3, 8, 102)
    # We concat the input with itself for simplicity
    v_cat = ops.concat([v_in, v_in], axis=2, name="v_cat")

    # 3. ReduceMax along axis 2
    # Expected: (3, 8) if keep_dims=False
    # Bug: Returns (3, 8, 51)
    axis = ops.constant([2], np.int64)
    v_out = ops.reduce_max(v_cat, axis, keep_dims=False, name="v_out")

    model = ov.Model([v_out], [v_in])
    return model

def main():
    core = ov.Core()
    
    # Data Preparation
    input_shape = (3, 8, 51)
    data = np.random.randn(*input_shape).astype(np.float32)

    print(f"Testing Concat+Reduce on Axis 2...")
    
    # Compile
    model = build_buggy_graph_reducemax_axis2()
    compiled_model = core.compile_model(model, "CPU")
    
    # Infer
    res = compiled_model.infer_new_request([data])[compiled_model.output(0)]
    
    print("-" * 40)
    print(f"Input Shape:      {input_shape}")
    print(f"Expected Output:  (3, 8)")
    print(f"Actual OV Output: {res.shape}")
    print("-" * 40)

    # Verification
    if res.shape == input_shape:
        print("[FAIL] Bug Reproduced: Output shape matches Input shape (Leakage).")
        print("The ReduceMax operation was effectively ignored.")
    else:
        print("[PASS] Shape is correct.")

if __name__ == "__main__":
    main()

### Relevant log output

```shell
Testing Concat+Reduce on Axis 2...
----------------------------------------
Input Shape:      (3, 8, 51)
Expected Output:  (3, 8)
Actual OV Output: (3, 8, 51)
----------------------------------------
[FAIL] Bug Reproduced: Output shape matches Input shape (Leakage).
The ReduceMax operation was effectively ignored.
```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

### PR DESCRIPTION
**Pull request by Yash-Vijay29**
### Details:
-Fusing Concat+Reduce into Max/Min is only valid if the operation matches element-wise Max/Min.
-This requires that the concatenation only merged "single" elements along that axis, so that Max(A, B) is equivalent to ReduceMax(Concat(A, B)).
-If inputs have dimension > 1 along the concat axis, ReduceMax performs a reduction within A and within B,
-which Average/Max/Min(A, B) does not capture (it broadcasts instead).
 - Fixes #33375
- Fixes #33389
- Fixes #33391

### CODE REVIEW

File: src/frontends/pytorch/src/op_table.cpp [hunk 1]
```diff
@@ -95,6 +95,7 @@ OP_CONVERTER(translate_expm1);
 OP_CONVERTER(translate_eye);
 OP_CONVERTER(translate_fake_quantize_per_channel_affine);
 OP_CONVERTER(translate_fake_quantize_per_tensor_affine);
```
Comment (Yash-Vijay29) [inline src/frontends/pytorch/src/op_table.cpp:97]: Remove this part accidentally added it here, from another issue

**Comment by Yash-Vijay29** [comment]
the only commit to see is the "[modified concat_reduce_fusion](https://github.com/openvinotoolkit/openvino/pull/33384/commits/b472b852c0a78447ee8c7169ca061610c2e22df5)" rest were accidentally committed from another issue

File: src/frontends/pytorch/src/op/fake_quantize.cpp
Comment (Yash-Vijay29) [inline src/frontends/pytorch/src/op/fake_quantize.cpp:1]: from another issue,  committed accidentally

**Comment by cknd** [comment]
does this also fix https://github.com/openvinotoolkit/openvino/issues/33295 ?

File: src/frontends/pytorch/src/op/fake_quantize.cpp
Comment (mitruska) [reply src/frontends/pytorch/src/op/fake_quantize.cpp:1]: Please revert all accidental changes (deleted files).

File: src/frontends/pytorch/src/op_table.cpp
Comment (mitruska) [inline src/frontends/pytorch/src/op_table.cpp:1]: This file shouldn't be removed, please revert.

File: tests/layer_tests/pytorch_tests/test_fake_quantize.py
Comment (mitruska) [inline tests/layer_tests/pytorch_tests/test_fake_quantize.py:1]: This file shouldn't be removed, please revert.

File: src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp [hunk 2]
```diff
@@ -106,6 +106,28 @@ ov::pass::ReplaceConcatReduceByMinOrMax::ReplaceConcatReduceByMinOrMax() {
...
+        // If inputs have dimension > 1 along the concat axis, ReduceMax performs a reduction within A and within B,
+        // which Average/Max/Min(A, B) does not capture (it broadcasts).
+        int64_t concat_axis = concat->get_axis();
+        for (const auto& input : concat->inputs()) {
+            const auto& p_shape = input.get_partial_shape();
+            if (p_shape.rank().is_dynamic()) {
+                return false;
+            }
+            int64_t rank = p_shape.rank().get_length();
+            int64_t norm_axis = concat_axis < 0 ? concat_axis + rank : concat_axis;
```
Comment (mitruska) [inline src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp]:
```suggestion
            const int64_t rank = p_shape.rank().get_length();
            const int64_t norm_axis = concat_axis < 0 ? concat_axis + rank : concat_axis;
```

File: src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp [hunk 3]
```diff
@@ -106,6 +106,28 @@ ov::pass::ReplaceConcatReduceByMinOrMax::ReplaceConcatReduceByMinOrMax() {
             return false;
         }
 
+        // Fusing Concat+Reduce into Max/Min is only valid if the operation matches element-wise Max/Min.
+        // This requires that the concatenation only merged "single" elements along that axis,
+        // so that Max(A, B) is equivalent to ReduceMax(Concat(A, B)).
+        // If inputs have dimension > 1 along the concat axis, ReduceMax performs a reduction within A and within B,
+        // which Average/Max/Min(A, B) does not capture (it broadcasts).
```
Comment (mitruska) [inline src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp]: Provided explanation is reasonable and match the issue root cause, well described.
```suggestion

        // Fusing Concat+Reduce into Max/Min is only valid if the operation matches element-wise Max/Min.
        // This requires that the concatenation only merged "single" elements along that axis,
        // so that Max(A, B) is equivalent to ReduceMax(Concat(A, B)).
        // If inputs have dimension > 1 along the concat axis, ReduceMax performs a reduction within A and within B,
        // which Max/Min(A, B) does not capture (it broadcasts).
```

File: src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp [hunk 4]
```diff
@@ -106,6 +106,28 @@ ov::pass::ReplaceConcatReduceByMinOrMax::ReplaceConcatReduceByMinOrMax() {
...
+        int64_t concat_axis = concat->get_axis();
+        for (const auto& input : concat->inputs()) {
+            const auto& p_shape = input.get_partial_shape();
+            if (p_shape.rank().is_dynamic()) {
+                return false;
```
Comment (mitruska) [inline src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp]: Such check can be a part of the pattern.
Example: 
https://github.com/openvinotoolkit/openvino/blob/06c8f8a5e22642792e1260499e887ede20f02d8c/src/common/transformations/src/transformations/common_optimizations/reshape_prelu.cpp#L22-L23

Comment (mitruska) [reply src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp]: While it's reasonable to restrict this transformation for static rank only, it can be not backward compatible and some of the tests need to be adjusted if decided to proceed with such change:

https://github.com/openvinotoolkit/openvino/blob/77f747b83e3bcf0b21a2e6a675641ceec44c8ae6/src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp#L90-L95

**Comment by Yash-Vijay29** [comment]
@mitruska  hey there! i modified accordingly: 
1. Pattern Matching Approach (following reshape_prelu.cpp lines 22-23):

Added pattern::has_static_rank() predicates to concat inputs
Simplified callback by removing redundant dynamic rank checks
Pattern now enforces static rank requirement upfront

2. Test Updates (backward-incompatible change):

ConcatReduceMaxFusionDynamicRank test: Now expects NO transformation
ConcatReduceMinFusionDynamicRank test: Now expects NO transformation
Both tests now keep Concat + Reduce instead of transforming to Max/Min

see if it seems alright. Also removed the edits from a different PR

**Comment by Yash-Vijay29** [comment]
@mitruska erm would you know where i can check the code style guidelines to fix the code style issues

**Comment by mitruska** [comment]
> @mitruska erm would you know where i can check the code style guidelines to fix the code style issues

Please refer to: [OpenVINO Coding Guidelines - Coding style](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/coding_style.md)

File: src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp [hunk 5]
```diff
@@ -110,8 +110,19 @@ TEST_F(TransformationTestsF, ConcatReduceMaxFusionDynamicRank) {
...
+            std::make_shared<v0::Unsqueeze>(right_input, v0::Constant::create(element::i64, Shape{}, {reduce_axis}));
+
+        auto concat = std::make_shared<v0::Concat>(NodeVector{left_unsqueeze, right_unsqueeze}, reduce_axis);
+
+        auto reduce_max =
+            std::make_shared<v1::ReduceMax>(concat, v0::Constant::create(element::i64, Shape{}, {reduce_axis}));
+
+        // With dynamic rank, transformation should NOT apply
+        model_ref = std::make_shared<Model>(OutputVector{reduce_max}, ParameterVector{left_input, right_input});
     }
```
Comment (mitruska) [inline src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp]: If the test expect that transformation will be not applied (and the original model will be not changed) the model_ref part can be simply skipped, so the line 110-126 can be removed.
But for clarity the comment about the reason can be kept.
(Same for ConcatReduceMinFusionDynamicRank)

File: src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp
Comment (mitruska) [inline src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp:1]: As I previously mentioned, beside alignment of the existing tests, new tests need to be added to cover the fixed issue and applied changes. Please ensure that cases with keep_dims false and true are included.

For example:

```
+TEST_F(TransformationTestsF, ConcatReduceNoFusionNoBroadcast) {
+    PartialShape left_shape{8, 1, 5};
+    PartialShape right_shape{8, 4, 5};
+    std::int64_t concat_axis = 1;
+    std::int64_t reduce_axis = 1;
+    {
+        auto left_input = std::make_shared<v0::Parameter>(element::f64, left_shape);
+        auto right_input = std::make_shared<v0::Parameter>(element::f64, right_shape);
+
+        auto concat = std::make_shared<v0::Concat>(NodeVector{left_input, right_input}, concat_axis);
+        auto reduce_min =
+            std::make_shared<v1::ReduceMin>(concat, v0::Constant::create(element::i64, Shape{}, {reduce_axis}), false);
+
+        model = std::make_shared<Model>(OutputVector{reduce_min}, ParameterVector{left_input, right_input});
+        manager.register_pass<ov::pass::ConcatReduceFusion>();
+    }
+    // Reference model should remain unchanged - no fusion should occur
+}

+TEST_F(TransformationTestsF, ConcatReduceMinFusionNoUnsqueezeSingleDimStaticShape) {
+    PartialShape shape{2, 5, 3, 1, 4};
+    std::int64_t reduce_axis = 3;
+    {
+        auto left_input = std::make_shared<v0::Parameter>(element::f32, shape);
+        auto right_input = std::make_shared<v0::Parameter>(element::f32, shape);
+        auto concat = std::make_shared<v0::Concat>(NodeVector{left_input, right_input}, reduce_axis);
+
+        auto reduce_min =
+            std::make_shared<v1::ReduceMin>(concat, v0::Constant::create(element::i64, Shape{}, {reduce_axis}));
+
+        model = std::make_shared<Model>(OutputVector{reduce_min}, ParameterVector{left_input, right_input});
+        manager.register_pass<ov::pass::ConcatReduceFusion>();
+    }
+    {
+        auto left_input = std::make_shared<v0::Parameter>(element::f32, shape);
+        auto right_input = std::make_shared<v0::Parameter>(element::f32, shape);
+        auto minimum = std::make_shared<v1::Minimum>(left_input, right_input);
+        // Keep dims is false - so Squeeze has been inserted after Minimum
+        // Then Squeeze is replaced with Reshape by EliminateSqueeze pass
+        auto reshape = std::make_shared<v1::Reshape>(
+            minimum,
+            v0::Constant::create(element::i64, Shape{4}, std::vector<int64_t>{2, 5, 3, 4}),
+            false);
+        model_ref = std::make_shared<Model>(OutputVector{reshape}, ParameterVector{left_input, right_input});
+    }
+    comparator.enable(FunctionsComparator::CmpValues::ACCURACY);
+}
+
+TEST_F(TransformationTestsF, ConcatReduceMinFusionNoUnsqueezeSingleDimStaticShapeKeepDims) {
+    PartialShape shape{2, 5, 3, 1, 4};
+    std::int64_t reduce_axis = 3;
+    bool keep_dims = true;
+    {
+        auto left_input = std::make_shared<v0::Parameter>(element::f32, shape);
+        auto right_input = std::make_shared<v0::Parameter>(element::f32, shape);
+        auto concat = std::make_shared<v0::Concat>(NodeVector{left_input, right_input}, reduce_axis);
+
+        auto reduce_min = std::make_shared<v1::ReduceMin>(concat,
+                                                          v0::Constant::create(element::i64, Shape{}, {reduce_axis}),
+                                                          keep_dims);
+        model = std::make_shared<Model>(OutputVector{reduce_min}, ParameterVector{left_input, right_input});
+        manager.register_pass<ov::pass::ConcatReduceFusion>();
+    }
+    {
+        auto left_input = std::make_shared<v0::Parameter>(element::f32, shape);
+        auto right_input = std::make_shared<v0::Parameter>(element::f32, shape);
+        auto minimum = std::make_shared<v1::Minimum>(left_input, right_input);
+        model_ref = std::make_shared<Model>(OutputVector{minimum}, ParameterVector{left_input, right_input});
+    }
+    comparator.enable(FunctionsComparator::CmpValues::ACCURACY);
+}
```
Hint - to ensure equal results from both graphs, worth to add ACCURACY comparator when reasonable, like:
` comparator.enable(FunctionsComparator::CmpValues::ACCURACY);`

File: src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp [hunk 6]
```diff
@@ -107,6 +109,26 @@ ReplaceConcatReduceByMinOrMax::ReplaceConcatReduceByMinOrMax() {
...
+        // This requires that the concatenation only merged "single" elements along that axis,
+        // so that Max(A, B) is equivalent to ReduceMax(Concat(A, B)).
+        // If inputs have dimension > 1 along the concat axis, ReduceMax performs a reduction within A and within B,
+        // which Average/Max/Min(A, B) does not capture (it broadcasts).
+        int64_t concat_axis = concat->get_axis();
+        for (const auto& input : concat->inputs()) {
+            const auto& p_shape = input.get_partial_shape();
+            // Rank is guaranteed static by pattern predicates
+            const int64_t rank = p_shape.rank().get_length();
+            const int64_t norm_axis = concat_axis < 0 ? concat_axis + rank : concat_axis;
```
Comment (mryzhov) [inline src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp]: you can use ov::util::normalize_axis() from src/core/src/validation_util.cpp

Comment (Yash-Vijay29) [reply src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp]: aha thank you will do so

File: src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp [hunk 7]
```diff
@@ -107,12 +108,7 @@ TEST_F(TransformationTestsF, ConcatReduceMaxFusionDynamicRank) {
         model = std::make_shared<Model>(OutputVector{reduce_max}, ParameterVector{left_input, right_input});
         manager.register_pass<ov::pass::ConcatReduceFusion>();
     }
-    {
-        auto left_input = std::make_shared<v0::Parameter>(element::f32, shape);
-        auto right_input = std::make_shared<v0::Parameter>(element::f32, shape);
-        auto maximum = std::make_shared<v1::Maximum>(left_input, right_input);
-        model_ref = std::make_shared<Model>(OutputVector{maximum}, ParameterVector{left_input, right_input});
-    }
+    // With dynamic rank, transformation should NOT apply - model remains unchanged
```
Comment (mryzhov) [inline src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp:111]:
```suggestion
    // With dynamic rank, transformation should NOT apply - model remains unchanged
    model_ref = model.clone();
```

File: src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp [hunk 8]
```diff
@@ -163,12 +159,7 @@ TEST_F(TransformationTestsF, ConcatReduceMinFusionDynamicRank) {
         model = std::make_shared<Model>(OutputVector{reduce_max}, ParameterVector{left_input, right_input});
         manager.register_pass<ov::pass::ConcatReduceFusion>();
     }
-    {
-        auto left_input = std::make_shared<v0::Parameter>(element::f32, shape);
-        auto right_input = std::make_shared<v0::Parameter>(element::f32, shape);
-        auto maximum = std::make_shared<v1::Minimum>(left_input, right_input);
-        model_ref = std::make_shared<Model>(OutputVector{maximum}, ParameterVector{left_input, right_input});
-    }
+    // With dynamic rank, transformation should NOT apply - model remains unchanged
```
Comment (mryzhov) [inline src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp:162]:
```suggestion
    // With dynamic rank, transformation should NOT apply - model remains unchanged
    model_ref = model.clone();
```

File: src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp [hunk 9]
```diff
@@ -107,6 +110,24 @@ ReplaceConcatReduceByMinOrMax::ReplaceConcatReduceByMinOrMax() {
...
+        // which Average/Max/Min(A, B) does not capture (it broadcasts).
+        int64_t concat_axis = concat->get_axis();
+        for (const auto& input : concat->inputs()) {
+            const auto& p_shape = input.get_partial_shape();
+            // Rank is guaranteed static by pattern predicates
+            const int64_t rank = p_shape.rank().get_length();
+            const auto norm_axis = ov::util::normalize_axis(concat_axis, rank);
+            
+            if (p_shape[norm_axis].is_dynamic() || p_shape[norm_axis].get_length() != 1) {
+
```
Comment (CuriousPanCake) [inline src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp:124]:
```suggestion
```

Comment (CuriousPanCake) [reply src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp:124]: Unnecessary newline

Comment (Yash-Vijay29) [reply src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp:124]: Ah okay, will work on it. Thanks for pointing out!

File: src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp (hunk 7 above)
Comment (mitruska) [reply src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp:111]: Actually it's a default behavior of the TransformationTestsF class https://github.com/openvinotoolkit/openvino/blob/08aa357021ee3c21a5b50647e306e6ce3ea33e75/src/tests/test_utils/common_test_utils/src/ov_test_utils.cpp#L70-L74

**Comment by Yash-Vijay29** [comment]
@mitruska added more tests as you recommended, and used ov::util:normalize_axis 

Hopefully code style issues are gone.

While building completely failed on my device due to some intel gpu kernel error, i think it successfully built the concat_reduce_fusion logic. 

Can you run the checks and let me know if its code style is fine + other recommendations?

**Comment by mitruska** [comment]
build_jenkins

**Comment by mitruska** [comment]
build_jenkins

File: src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp [hunk 10]
```diff
@@ -107,6 +110,23 @@ ReplaceConcatReduceByMinOrMax::ReplaceConcatReduceByMinOrMax() {
         if (!reduce || !concat)
             return false;
 
+        // Fusing Concat+Reduce into Max/Min is only valid if the operation matches element-wise Max/Min.
+        // This requires that the concatenation only merged "single" elements along that axis,
+        // so that Max(A, B) is equivalent to ReduceMax(Concat(A, B)).
+        // If inputs have dimension > 1 along the concat axis, ReduceMax performs a reduction within A and within B,
+        // which Average/Max/Min(A, B) does not capture (it broadcasts).
```
Comment (evkotov) [inline src/common/transformations/src/transformations/common_optimizations/concat_reduce_fusion.cpp]: Comment mentions "Average" but the transformation only handles ReduceMax and ReduceMin, not ReduceMean. Consider changing "Average/Max/Min(A, B)" to "Max/Min(A, B)" or "Maximum/Minimum(A, B)".

File: src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp [hunk 11]
```diff
@@ -292,3 +283,133 @@ TEST_F(TransformationTestsF, PullSqueezeThroughEltwiseSqueezeEliminationDynamicR
         model_ref = std::make_shared<Model>(OutputVector{add}, ParameterVector{left_input, right_input});
     }
 }
+
```
Comment (evkotov) [inline src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp:286]: Consider to add a test for static rank with dynamic dimension along concat axis.

Example: shape [-1, -1, -1, -1] with concat/reduce on axis where dim is unknown.
The existing ConcatReduceMaxFusionDynamicShape test uses Unsqueeze which creates
static dim=1. A direct test with dynamic dim along concat axis would verify
that transformation is skipped when we cannot statically confirm dim=1

Comment (Yash-Vijay29) [reply src/common/transformations/tests/common_optimizations/concat_reduce_fusion.cpp:286]: Ok will do so

**Comment by mryzhov** [comment]
@Yash-Vijay29 thanks a lot for your contribution!

**Comment by mryzhov** [comment]
build_jenkins
