### PR TITLE
[TF FE][TF Hub] Support Xlogy operation

### LINKED ISSUE #20452: [Good First Issue]: Support Xlogy operation for TensorFlow models
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.1/openvino_docs_ops_opset.html).

In order to infer TensorFlow models with [Xlogy](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Xlogy) operation by OpenVINO, TF FE needs to be extended with this operation support.

### What needs to be done?

For [Xlogy](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Xlogy) operation support, you need to add the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

Here is an example of loader implementation for TensorFlow `Einsum` operation:

```cpp
OutputVector translate_einsum_op(const NodeContext& node) { 
     auto op_type = node.get_op_type(); 
     TENSORFLOW_OP_VALIDATION(node, op_type == "Einsum", "Internal error: incorrect usage of translate_einsum_op."); 
     auto equation = node.get_attribute<std::string>("equation"); 
  
     OutputVector inputs; 
     for (size_t input_ind = 0; input_ind < node.get_input_size(); ++input_ind) { 
         inputs.push_back(node.get_input(input_ind)); 
     } 
  
     auto einsum = make_shared<Einsum>(inputs, equation); 
     set_node_name(node.get_name(), einsum); 
     return {einsum}; 
 } 
```

In this example, `translate_einsum_op` converts TF `Einsum` into OV `Einsum`. `NodeContext` object passed into the loader packs all info about inputs and attributes of `Einsum` operation. The loader retrieves an attribute of the equation by using the `NodeContext::get_attribute()` method, prepares input vector, creates `Einsum` operation from OV opset and returns a vector of outputs.

Responsibility of a loader is to parse operation attributes, prepare inputs and express TF operation via OV operations sub-graph. Example for `Einsum` demonstrates the resulted sub-graph with one operation. In PR https://github.com/openvinotoolkit/openvino/pull/19007 you can see operation decomposition into multiple node sub-graph.

### Example Pull Requests

https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/README.md)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers

### Ticket

TBD

### PR DESCRIPTION
**Pull request by siddhant-0707**
### Details:
 - Support Xlogy operation for TF Hub Models

### Tickets:
 - Closes #20452

### CODE REVIEW

File: src/frontends/tensorflow_common/src/op/xlogy.cpp [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+namespace tensorflow {
+namespace op {
+OutputVector translate_xlogy_op(const NodeContext& node) {
+    default_op_checks(node, 2, {"Xlogy"});
+    auto x = node.get_input(0);
+    auto y = node.get_input(1);
+
+    // prepare auxiliary zero constant of the same type as the input
+    auto zero = make_shared<Constant>(element::f32, Shape{}, 0.0f)->output(0);
+    zero = make_shared<ConvertLike>(zero, x);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/xlogy.cpp:27]: Please use helper from `utils.hpp`:

```
auto zero = create_same_type_const_scalar<int32_t>(x, 0);
```

File: tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+class TestXlogy(CommonTFLayerTest):
+    def _prepare_input(self, inputs_info):
+        assert 'x' in inputs_info
+        assert 'y' in inputs_info
+        x_shape = inputs_info['x']
+        y_shape = inputs_info['y']
+        inputs_data = {}
+        # generate x in way to have zeros
+        inputs_data['x'] = np.random.randint(-10, 10, y_shape).astype(self.input_type) * \
+                           np.random.randint(0, 2, y_shape).astype(self.input_type)
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py:19]:
```suggestion
        inputs_data['x'] = np.random.randint(-10, 10, x_shape).astype(self.input_type) * \
                           np.random.randint(0, 2, x_shape).astype(self.input_type)
```

File: tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py [hunk 3]
```diff
@@ -0,0 +1,48 @@
...
+        inputs_data['y'] = np.random.randint(-10, 10, x_shape).astype(self.input_type)
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py:20]:
```suggestion
        inputs_data['x'] = np.random.randint(-10, 10, x_shape).astype(self.input_type) * \
                           np.random.randint(0, 2, x_shape).astype(self.input_type)
        inputs_data['y'] = np.random.randint(-10, 10, y_shape).astype(self.input_type)
```

**Review by rkazants — APPROVED** [review]

File: tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+    def _prepare_input(self, inputs_info):
+        assert 'x' in inputs_info
+        assert 'y' in inputs_info
+        x_shape = inputs_info['x']
+        y_shape = inputs_info['y']
+        inputs_data = {}
+        # generate x in way to have zeros
+        inputs_data['x'] = np.random.randint(-10, 10, x_shape).astype(self.input_type) * \
+                           np.random.randint(0, 2, x_shape).astype(self.input_type)
+        inputs_data['y'] = np.random.randint(-10, 10, y_shape).astype(self.input_type)
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py:20]: please use float generation: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html
x from range [-3, 3] and y from range [1, 2] (let us exclude 0 because we have a bug in layer test results comparation that nans are not equal).

File: tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+        assert 'x' in inputs_info
+        assert 'y' in inputs_info
+        x_shape = inputs_info['x']
+        y_shape = inputs_info['y']
+        inputs_data = {}
+        # x = [-3 ,3] y = [1, 2]
+        # generate x in way to have zeros
+        inputs_data['x'] = (6 * np.random.random(size=x_shape, dtype=np.float32) - 3) * \
+                            np.random.randint(2, size=x_shape, dtype=np.float32)
+        inputs_data['y'] = np.random.random(size=y_shape, dtype=np.float32) + 1
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py:21]: Please fix `TypeError: random() got an unexpected keyword argument 'dtype'
`

File: tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py [hunk 6]
```diff
@@ -0,0 +1,49 @@
...
+        assert 'x' in inputs_info
+        assert 'y' in inputs_info
+        x_shape = inputs_info['x']
+        y_shape = inputs_info['y']
+        inputs_data = {}
+        # x = [-3 ,3] y = [1, 2]
+        # generate x in way to have zeros
+        inputs_data['x'] = (6 * np.random.random(size=x_shape, dtype=np.float32) - 3) * \
+                            np.random.randint(2, size=x_shape).astype(np.float32)
+        inputs_data['y'] = np.random.random(size=y_shape, dtype=np.float32) + 1
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py:21]:
```suggestion
        inputs_data['x'] = (6 * np.random.random(size=x_shape).astype(np.float32) - 3) * \
                            np.random.randint(2, size=x_shape, dtype=np.float32)
        inputs_data['y'] = np.random.random(size=y_shape).astype(np.float32) + 1
```

**Comment by rkazants** [comment]
build_jenkins

File: tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py [hunk 7]
```diff
@@ -0,0 +1,49 @@
...
+        assert 'x' in inputs_info
+        assert 'y' in inputs_info
+        x_shape = inputs_info['x']
+        y_shape = inputs_info['y']
+        inputs_data = {}
+        # x = [-3 ,3] y = [1, 2]
+        # generate x in way to have zeros
+        inputs_data['x'] = (6 * np.random.random(size=x_shape).astype(np.float32) - 3) * \
+                            np.random.randint(2, size=x_shape, dtype=np.float32)
+        inputs_data['y'] = np.random.random(size=y_shape).astype(np.float32) + 1
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Xlogy.py:21]:
```suggestion
        inputs_data['x'] = (6 * np.random.random(size=x_shape).astype(np.float32) - 3) * \
                            np.random.randint(2, size=x_shape).astype(np.float32)
        inputs_data['y'] = np.random.random(size=y_shape).astype(np.float32) + 1
```

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
build_jenkins
