### PR TITLE
fix race condition in layout attribute visiting

### LINKED ISSUE #21456: [Bug]: "AUTO" device can sometimes cause the program to crash
### OpenVINO Version

2023.0.1

### Operating System

Other (Please specify in description)

### Device used for inference

AUTO

### Framework

None

### Model used

_No response_

### Issue description

OS: Ubuntu 22.0.4

With the reasoning device set to "AUTO", sometimes turning on reasoning will cause a crash, the specific crash stack is as follows.
dump

### Step-by-step reproduction

_No response_

### Relevant log output

_No response_

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.

- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

### PR DESCRIPTION
**Pull request by songbell**
### Details:
 - fix race condition in layout attribute visiting

### Tickets:
 - Closes #21456

### CODE REVIEW

File: src/core/src/layout.cpp [hunk 1]
```diff
@@ -638,6 +638,7 @@ void AttributeAdapter<ov::Layout>::set(const std::string& value) {
 }
 
 bool LayoutAttribute::visit_attributes(AttributeVisitor& visitor) {
+    std::lock_guard<std::mutex> lock{*m_mutex.get()};
```
Comment (vurusovs) [inline src/core/src/layout.cpp:641]: @songbell could you explain how it should solve the issue?

Comment (songbell) [reply src/core/src/layout.cpp]: I analyzed from the limited trace from user, it should be the race condition issue happened in ov::Hash pass, because auto will do thread compilation to multiple devices. I have enabled tests, please help a check.

File: src/core/src/layout.cpp [hunk 2]
```diff
@@ -640,7 +640,11 @@ void AttributeAdapter<ov::Layout>::set(const std::string& value) {
 bool LayoutAttribute::visit_attributes(AttributeVisitor& visitor) {
     std::string layout_str = value.to_string();
     visitor.on_attribute("layout", layout_str);
-    value = Layout(layout_str);
+    // some attribute visitor will not change the value
+    // for example, rt info serializer
+    // in this case, parallelization can be supported in hash pass
+    if (layout_str != value.to_string())
```
Comment (praasz) [inline src/core/src/layout.cpp:646]: How this check fix race condition? Can you explain?
I think it only reduce chance as number of writes to `value` will reduced.

Comment (songbell) [reply src/core/src/layout.cpp:646]: Hi @praasz , generally visitors are able to change the attribute values and callers are responsible for the thread-safe.
while in this bug, the visitor is rt info serializer from ov::Hash pass, which will only read the value, so the fix here is to avoid unnecessary change of value. otherwise, we have to add global mutex in icore before do hashing.

Comment (riverlijunjie) [reply src/core/src/layout.cpp:646]: The presented solution can decrease the reproduced probability but cannot avoid race-condition completely. Considered the original probability is very low, I likely don't think we have enough motivation to add extra global mutex.

**Comment by wenjiew** [comment]
Please help with the code review. Thanks!

File: src/core/src/layout.cpp (hunk 2 above)
Comment (praasz) [reply src/core/src/layout.cpp:646]: As you mention this solution reduce probability not fix. Consider create follow-up ticket to fix root cause (not necessary by using mutex).
It looks like issue is when visiting attribute with same value it want change it but will write (this fix reduce such writes). If `ov::Hash` just reads attribute then maybe visitor should only access it for reading and not change it e.g usign visitor like const object, but when visitor could change value use it as non-const. But it requires more investigate and I don't have solution now.

**Review by praasz — APPROVED** [review]

**Review by riverlijunjie — APPROVED** [review]

**Review by vurusovs — APPROVED** [review]
