### PR TITLE
[Fix] Unexpected exception information of BATCH plugin

### LINKED ISSUE #23125: [Good First Issue]: Throw exception for invalid device list to BATCH
### Context

Following executions should throw correct exception.
```
python3 -c "import openvino; openvino.Core().compile_model(<model path>, 'BATCH:-GPU')" 
Execute successfully
```

**Expected behavior:** Throw exception "Invalid device name '-GPU' for BATCH"

```
python3 -c "import openvino; openvino.Core().compile_model(<model path>, 'BATCH:GPU,CPU')" 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/openvino-ci-42/peter/py39/lib/python3.9/site-packages/openvino/runtime/ie_api.py", line 547, in compile_model
    super().compile_model(model, device_name, {} if config is None else config),
RuntimeError: Exception from src/inference/src/core.cpp:116:
[ GENERAL_ERROR ] Exception from src/inference/src/dev/core_impl.cpp:560:
Device with "GPU,CPU" name is not registered in the OpenVINO Runtime
```
**Expected behavior:** Throw exception "BATCH accepts only one device in list."

### What needs to be done?

Validate the device name in BATCH plugin while doing the compile_model

### Example Pull Requests

_No response_

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [BATCH user guide](https://docs.openvino.ai/2023.3/openvino_docs_OV_UG_Automatic_Batching.html)
- [Intel DevHub Discord channel](https://discord.gg/7pVRxUwdWG) - engage in discussions, ask questions and talk to OpenVINO developers

### Contact points

@zhaixuejun1993  @riverlijunjie  @ilya-lavrenov @vurusovs @peterchen-intel

### Ticket

CVS-132276

### PR DESCRIPTION
**Pull request by AsakusaRinne**
### Details:
 - Throw exception when detecting wrong format like '-GPU' in BATCH.
 - Throw exception with right information when getting multiple devices for BATCH.

### Tickets:
 - CVS-132276

### Related issues:
 - Closes #23125

### CODE REVIEW

File: src/inference/src/dev/core_impl.cpp [hunk 1]
```diff
@@ -994,6 +994,18 @@ ov::SoPtr<ov::IRemoteContext> ov::CoreImpl::get_default_context(const std::strin
     return get_plugin(parsed._deviceName).get_default_context(parsed._config);
 }
 
+void validate_batch_device_name(const std::string& deviceName) {
+    auto name = deviceName;
+    auto pos = name.find(",");
+    // for trailing comma such as "gpu,", we do not treat it as multi-device.
```
Comment (riverlijunjie) [inline src/inference/src/dev/core_impl.cpp:1000]: For similar "gpu," case, we should treat it as invalid device to throw exception rather than fix it.

File: src/plugins/auto_batch/src/plugin.cpp [hunk 2]
```diff
@@ -136,6 +136,9 @@ std::shared_ptr<ov::ICompiledModel> Plugin::compile_model(const std::shared_ptr<
 
     const auto& device_name = meta_device.device_name;
     const auto& device_config = meta_device.device_config;
+    if (auto pos = device_name.find("-") != std::string::npos) {
+        OPENVINO_THROW("Invalid device name '", device_name, "' for BATCH");
+    }
```
Comment (riverlijunjie) [inline src/plugins/auto_batch/src/plugin.cpp:141]: Will be better if move this checking into `validate_batch_device_name`?

File: src/inference/src/dev/core_impl.cpp (hunk 1 above)
Comment (AsakusaRinne) [reply src/inference/src/dev/core_impl.cpp]: I've modified the logic here, thank you for the comment!

File: src/plugins/auto_batch/src/plugin.cpp (hunk 2 above)
Comment (AsakusaRinne) [reply src/plugins/auto_batch/src/plugin.cpp]: I've moved it to `validate_batch_device_name`. :)

File: src/inference/src/dev/core_impl.cpp [hunk 3]
```diff
@@ -1008,6 +1018,7 @@ std::shared_ptr<const ov::Model> ov::CoreImpl::apply_auto_batching(const std::sh
 
         deviceNameWithBatchSize = deviceName.substr(pos + 1);
         deviceNameWithoutBatch = ov::DeviceIDParser::get_batch_device(deviceNameWithBatchSize);
```
Comment (ilya-lavrenov) [inline src/inference/src/dev/core_impl.cpp:1020]: should we insert the logic directly to `ov::DeviceIDParser::get_batch_device`?
It's responsible for parsing and, hence, for validation

**Comment by riverlijunjie** [comment]
@AsakusaRinne some test cases need to be added for it: https://github.com/openvinotoolkit/openvino/blob/master/src/inference/tests/unit/core.cpp

**Comment by AsakusaRinne** [comment]
@ilya-lavrenov @riverlijunjie I've followed your suggestions and added unit test for it. Could you please help to review this PR again? : )

**Review by ilya-lavrenov — APPROVED** [review]

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Comment by AsakusaRinne** [comment]
@riverlijunjie Could you please take a look at the ci? It failed but it seems not related with my code. Maybe re-running them will resolve it?

**Comment by AsakusaRinne** [comment]
The ci failed again after the retry. Could you please help to see what happened? @ilya-lavrenov @riverlijunjie 

One of the windows ci shown a pip package conflict, as bellow. I'm not sure if it's introduced by another recent PR because I didn't modify python code in this PR.

```
The conflict is caused by:
    The user requested PyYAML
    The user requested (constraint) pyyaml>=5.4.1
```

There's also a linux ci failed but I could not open the link.

BTW I see there's a button `Update branch` to merge the latest master branch commits into my code. I'll click it and hope it will help.

Thank you for looking into this issue!

**Comment by ilya-lavrenov** [comment]
build_jenkins

**Review by riverlijunjie — APPROVED** [review]

**Review by wangleis — APPROVED** [review]
