### PR TITLE
[core] Recover from model cache write failures

### LINKED ISSUE #20190: [Good First Issue][GPU]: Cannot load model when cache directory is running out of disk space
### Context

GPU plugin utilizes cache files when loading models. When the cache is full, loading another model fails with:

```bash
~/pgladkow/openvino_repro/build$ ./test_ov
terminate called after throwing an instance of 'ov::Exception'
  what():  cldnn program build failed! clCreateProgramWithBinary
Aborted 
```

This task regards solving that issue.

### What needs to be done?

The cache should be cleared when not needed. Details should be discussed with people from Contact Points section.

Steps to reproduce:

1. Get `ov.cpp` (attachment)
2. Get `CMakeLists.txt` (attachment)
3. Mount cache directory to have a limited disk space (10m)
```bash
sudo mount -t tmpfs -o size=10m tmpfs tmp_cache
```
4. Run OpenVINO app
```bash
~/pgladkow/openvino_repro/build$ cmake ../ovms
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/home/k8sworker/pgladkow/openvino_repro/build
~/pgladkow/openvino_repro/build$ cmake --build .
[100%] Built target test_ov
~/pgladkow/openvino_repro/build$ ./test_ov
Hello 
```
5. Verify that cache directory is full
```bash
~/pgladkow/openvino_repro$ ls tmp_cache/
```
6. Run OV app once again - it should fail this time
```bash
~/pgladkow/openvino_repro/build$ ./test_ov
terminate called after throwing an instance of 'ov::Exception'
  what():  cldnn program build failed! clCreateProgramWithBinary
Aborted 
```

Directory structure from the original reproducer:
```bash
~/pgladkow/openvino_repro$ tree
.
├── build
│   ├── CMakeCache.txt
│   ├── CMakeFiles
│   │   ├── 3.16.3
│   │   │   ├── CMakeCCompiler.cmake
│   │   │   ├── CMakeCXXCompiler.cmake
│   │   │   ├── CMakeDetermineCompilerABI_C.bin
│   │   │   ├── CMakeDetermineCompilerABI_CXX.bin
│   │   │   ├── CMakeSystem.cmake
│   │   │   ├── CompilerIdC
│   │   │   │   ├── a.out
│   │   │   │   ├── CMakeCCompilerId.c
│   │   │   │   └── tmp
│   │   │   └── CompilerIdCXX
│   │   │       ├── a.out
│   │   │       ├── CMakeCXXCompilerId.cpp
│   │   │       └── tmp
│   │   ├── cmake.check_cache
│   │   ├── CMakeDirectoryInformation.cmake
│   │   ├── CMakeError.log
│   │   ├── CMakeOutput.log
│   │   ├── CMakeTmp
│   │   ├── Makefile2
│   │   ├── Makefile.cmake
│   │   ├── progress.marks
│   │   ├── TargetDirectories.txt
│   │   └── test_ov.dir
│   │       ├── build.make
│   │       ├── cmake_clean.cmake
│   │       ├── CXX.includecache
│   │       ├── DependInfo.cmake
│   │       ├── depend.internal
│   │       ├── depend.make
│   │       ├── flags.make
│   │       ├── link.txt
│   │       ├── progress.make
│   │       └── src
│   │           └── ov.cpp.o
│   ├── cmake_install.cmake
│   ├── Makefile
│   └── test_ov
├── ovms
│   ├── CMakeLists.txt
│   └── src
│       ├── brain-tumor-segmentation-0002-2
│       │   └── 1
│       │       ├── brain-tumor-segmentation-0002.onnx
│       │       └── description.txt
│       ├── dummy
│       │   └── 1
│       │       ├── dummy.bin
│       │       └── dummy.xml
│       ├── inception-resnet-v2-tf
│       │   └── 1
│       │       ├── inception-resnet-v2-tf.bin
│       │       ├── inception-resnet-v2-tf.mapping
│       │       └── inception-resnet-v2-tf.xml
│       ├── ov.cpp
│       └── ssdlite_mobilenet_v2_ov
│           └── 1
│               ├── ssdlite_mobilenet_v2_ov.bin
│               ├── ssdlite_mobilenet_v2_ov.mapping
│               └── ssdlite_mobilenet_v2_ov.xml
└── tmp_cache 
```
[reproducer.zip](https://github.com/openvinotoolkit/openvino/files/12782876/reproducer.zip)

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@pgladkows 
@vladimir-paramuzov

Ticket: 104958

### PR DESCRIPTION
**Pull request by allnes**
## Summary

Make file-based model cache write failures recoverable and keep cache entries consistent.

Before this change, a cache write failure during model export could leave an invalid cache entry and break subsequent cache use.

After this change:
- file-based cache writes either complete successfully or the failed cache entry is removed
- recoverable cache export failures no longer fail model compilation
- the cache write path stays simple and writes directly to the final blob path

### Details:
- File-based cache writes directly to the final `.blob` path.
- Repeated writes to the same cache entry overwrite the existing blob.
- Existing blob permissions are temporarily relaxed before overwrite, then restored to read-only after a successful store.
- Cache export failures are handled in `CoreImpl`, which removes the failed cache entry on caching errors.
- Stream write failures remain recoverable and do not fail model compilation.
- GPU export failures that surface as `ov::Exception` are also treated as recoverable cache export failures.
- Other unexpected exceptions are still propagated.

### Result:
- before: a cache write failure could leave a broken cache entry and break subsequent cache use
- after: failed cache writes are discarded, cache state remains usable, and subsequent runs continue normally

### Tickets:
- CVS-104958

### AI Assistance:
- *AI assistance used: yes*

### CODE REVIEW

File: src/inference/src/cache_manager.hpp [hunk 1]
```diff
@@ -51,11 +64,45 @@ class FileStorageCacheManager final : public ICacheManager {
         // Fix the bug caused by pugixml, which may return unexpected results if the locale is different from "C".
         ScopedLocale plocal_C(LC_ALL, "C");
         const auto blob_path = get_blob_file(id);
-        std::ofstream stream(blob_path, std::ios_base::binary);
-        writer(stream);
-        stream.close();
-        std::filesystem::permissions(blob_path,
-                                     std::filesystem::perms::owner_read | std::filesystem::perms::group_read);
+        if (std::filesystem::exists(blob_path)) {
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp]: This is not correct it should always write to path.

File: src/inference/src/cache_manager.hpp [hunk 2]
```diff
@@ -51,11 +64,45 @@ class FileStorageCacheManager final : public ICacheManager {
...
+        const auto temp_blob_path = get_temp_blob_file(id);
+        std::error_code ec;
+        const auto cleanup_temp_blob = [&] {
+            ec.clear();
+            std::filesystem::remove(temp_blob_path, ec);
+        };
+        cleanup_temp_blob();
+        try {
+            std::ofstream stream;
+            stream.exceptions(std::ios_base::failbit | std::ios_base::badbit);
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp]: In case of this kind of error cache entry should be removed.
Model can be compiled but without storing the cache file.

This function should be simple and do write only


There is also SingleFileCache which should be adjusted also

File: src/inference/src/cache_manager.hpp [hunk 3]
```diff
@@ -37,6 +41,15 @@ class FileStorageCacheManager final : public ICacheManager {
         return m_cache_path / (blob_hash + ".blob");
     }
 
+    std::filesystem::path get_temp_blob_file(const std::string& blob_hash) const {
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp]: Temp files are not required.

File: src/inference/src/dev/core_impl.cpp [hunk 4]
```diff
@@ -1512,6 +1513,21 @@ ov::SoPtr<ov::ICompiledModel> ov::CoreImpl::compile_model_and_cache(ov::Plugin&
 
     auto compiled_model = context ? plugin.compile_model(model, context, cfg) : plugin.compile_model(model, cfg);
     if (cache_content.m_cache_manager && device_supports_model_caching(plugin)) {
+        const auto warn_cache_write_failure = [](std::exception_ptr ex_ptr) {
```
Comment (praasz) [inline src/inference/src/dev/core_impl.cpp]: Remove there is no decision to put this message now

**Review by praasz — CHANGES_REQUESTED** [review]

**Comment by allnes** [comment]
@praasz Updated.

The cache now writes directly to the final `.blob` path, without temp files.

The storage layer now only handles storage consistency:
- file-based cache removes a partially written blob on recoverable write/flush failure
- `SingleFileStorage` rolls back partial appends and restores a clean state on recoverable failures

`compile_model()` remains non-fatal for recoverable cache write failures, so the model is still returned without storing the failed cache entry.

Please take another look at the current version when convenient.

File: src/inference/src/dev/core_impl.cpp [hunk 5]
```diff
@@ -1546,9 +1547,10 @@ ov::SoPtr<ov::ICompiledModel> ov::CoreImpl::compile_model_and_cache(ov::Plugin&
                                                  header_size_alignment);
                 compiled_model->export_model(stream);
             });
-        } catch (...) {
-            cache_content.m_cache_manager->remove_cache_entry(cache_content.m_blob_id);
```
Comment (praasz) [inline src/inference/src/dev/core_impl.cpp:1550]: This must be restored.
In case of any caching error the cache entry should be removed.

File: src/inference/src/cache_manager.hpp [hunk 6]
```diff
@@ -51,32 +107,36 @@ class FileStorageCacheManager final : public ICacheManager {
...
-                CompiledBlobVariant compiled_blob{std::in_place_index<0>, ov::read_tensor_data(blob_path)};
-                reader(compiled_blob);
-            } else {
-                std::ifstream stream(blob_path, std::ios_base::binary);
-                CompiledBlobVariant compiled_blob{std::in_place_index<1>, std::ref(stream)};
-                reader(compiled_blob);
-            }
+
+        std::error_code ec;
+        const auto blob_size = std::filesystem::file_size(blob_path, ec);
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp]: Why this is changed?

File: src/inference/src/cache_manager.hpp [hunk 7]
```diff
@@ -51,32 +107,36 @@ class FileStorageCacheManager final : public ICacheManager {
         // Fix the bug caused by pugixml, which may return unexpected results if the locale is different from "C".
         ScopedLocale plocal_C(LC_ALL, "C");
         const auto blob_path = get_blob_file(id);
-        std::ofstream stream(blob_path, std::ios_base::binary);
-        writer(stream);
-        stream.close();
-        std::filesystem::permissions(blob_path,
-                                     std::filesystem::perms::owner_read | std::filesystem::perms::group_read);
+        if (has_non_empty_blob(blob_path)) {
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp]: It should be not required if empty path returned there should fail on write or do nothing on write

**Review by praasz — CHANGES_REQUESTED** [review]

File: src/inference/src/dev/core_impl.cpp (hunk 5 above)
Comment (allnes) [reply src/inference/src/dev/core_impl.cpp:1550]: Updated. `remove_cache_entry()` is restored in the cache error path, so the cache entry is removed on any caching error.

File: src/inference/src/cache_manager.hpp (hunk 6 above)
Comment (allnes) [reply src/inference/src/cache_manager.hpp]: Updated. I reverted this back to the simpler `exists(...)`-based read path.

File: src/inference/src/cache_manager.hpp (hunk 7 above)
Comment (allnes) [reply src/inference/src/cache_manager.hpp]: Updated. I removed the extra non-empty helper and kept the simpler `exists(...)` check before write.

File: src/inference/src/cache_manager.hpp (hunk 1 above)
Comment (praasz) [reply src/inference/src/cache_manager.hpp]: Still not corrected if we call write the blob should be overwritten there is no need to change and sub- functions here.

The logic should be simple the write fails witll throw. Core_impl logic should catch and call cache_remove_entry (if not exist just do nothing)


If store is with success the permission should be set.

File: src/inference/src/dev/core_impl.cpp [hunk 8]
```diff
@@ -1548,7 +1549,13 @@ ov::SoPtr<ov::ICompiledModel> ov::CoreImpl::compile_model_and_cache(ov::Plugin&
...
         } catch (...) {
             cache_content.m_cache_manager->remove_cache_entry(cache_content.m_blob_id);
-            throw;
+            try {
+                throw;
+            } catch (const std::filesystem::filesystem_error&) {
+                throw;
+            } catch (...) {
+                // Keep the compiled model on recoverable cache write failures.
+            }
```
Comment (praasz) [inline src/inference/src/dev/core_impl.cpp]: Why is required?
on any failure just remove cache and throw. Remove cache should not throw just remove or do nothing.

Comment (allnes) [reply src/inference/src/dev/core_impl.cpp]: I removed the nested `try/catch` here and simplified the flow:
  - `filesystem_error` -> remove cache entry and rethrow
  - other cache write failures -> remove cache entry and keep the compiled model

  I also restored setting permissions on successful blob write.

  The stricter `remove + throw on any failure` behavior would make recoverable cache export failures fatal again, which changes the intended behavior of this fix. The current
  behavior keeps the cache entry cleanup, but still allows model compilation to succeed when the cache write failure is recoverable.

File: src/inference/src/cache_manager.hpp [hunk 9]
```diff
@@ -51,11 +50,20 @@ class FileStorageCacheManager final : public ICacheManager {
...
+        try {
+            writer(stream);
+        } catch (const std::filesystem::filesystem_error& ex) {
+            throw std::ios_base::failure(ex.what());
+        }
+        stream.flush();
         stream.close();
         std::filesystem::permissions(blob_path,
-                                     std::filesystem::perms::owner_read | std::filesystem::perms::group_read);
+                                     std::filesystem::perms::owner_read | std::filesystem::perms::owner_write |
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp]: The blob should be set as read-only (that was security issue)

File: src/inference/src/cache_manager.hpp [hunk 10]
```diff
@@ -51,11 +50,20 @@ class FileStorageCacheManager final : public ICacheManager {
...
+
+        std::ofstream stream;
+        stream.exceptions(std::ios_base::failbit | std::ios_base::badbit);
+        stream.open(blob_path, std::ios_base::binary | std::ios_base::trunc);
+        try {
+            writer(stream);
+        } catch (const std::filesystem::filesystem_error& ex) {
+            throw std::ios_base::failure(ex.what());
+        }
+        stream.flush();
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp]: Is it required the `close()` should call flush

File: src/inference/src/cache_manager.hpp [hunk 11]
```diff
@@ -51,7 +50,19 @@ class FileStorageCacheManager final : public ICacheManager {
         // Fix the bug caused by pugixml, which may return unexpected results if the locale is different from "C".
         ScopedLocale plocal_C(LC_ALL, "C");
         const auto blob_path = get_blob_file(id);
-        std::ofstream stream(blob_path, std::ios_base::binary);
+
+        std::error_code ec;
+        if (std::filesystem::exists(blob_path)) {
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp:55]:
```suggestion
        if (ov::util::file_exists(blob_path)) {
```
Use it instead.

File: src/inference/src/cache_manager.hpp [hunk 12]
```diff
@@ -51,7 +50,19 @@ class FileStorageCacheManager final : public ICacheManager {
...
+            std::filesystem::permissions(blob_path,
+                                         std::filesystem::perms::owner_read | std::filesystem::perms::owner_write |
+                                             std::filesystem::perms::group_read,
+                                         std::filesystem::perm_options::replace,
+                                         ec);
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp:60]:
```suggestion
            std::filesystem::permissions(blob_path,
                                         std::filesystem::perms::owner_write ,
                                         std::filesystem::perm_options::add,
                                         ec);
```
Is `ec` required, or maybe it should throw, should be also use after file close?

Can be explain why is required, are there any case that without change it there is some kind of err on write?

File: src/inference/src/cache_manager.hpp [hunk 13]
```diff
@@ -51,7 +50,19 @@ class FileStorageCacheManager final : public ICacheManager {
...
+        }
+
+        std::ofstream stream;
+        stream.exceptions(std::ios_base::failbit | std::ios_base::badbit);
+        stream.open(blob_path, std::ios_base::binary | std::ios_base::trunc);
```
Comment (praasz) [inline src/inference/src/cache_manager.hpp:65]: why ` std::ios_base::trunc` added for output fstream it should not be required.

File: src/inference/src/single_file_storage.cpp [hunk 14]
```diff
@@ -337,11 +410,25 @@ void SingleFileStorage::initialize(std::shared_ptr<ov::wsh::Context> weight_shar
...
         OPENVINO_ASSERT(util::is_version_compatible(m_version, file_version), "Incompatible cache format");
-        OPENVINO_ASSERT(build_content_index(stream), "The cache file may be corrupted or in an unsupported format");
+        if (!build_content_index(stream)) {
+            try {
+                reset_single_file_storage_state(m_file_path, m_version, m_shared_context);
+            } catch (const std::exception& ex) {
+                throw std::filesystem::filesystem_error(
+                    "Failed to restore cache file after initialize failure: " + std::string(ex.what()),
+                    m_file_path,
+                    std::make_error_code(std::errc::io_error));
```
Comment (praasz) [inline src/inference/src/single_file_storage.cpp:425]: In OV code it should not be used.
Use OPENVINO_ASSERT|THROW

File: src/inference/src/single_file_storage.cpp [hunk 15]
```diff
@@ -237,11 +239,82 @@ void SingleFileStorage::write_blob_entry(std::fstream& stream, BlobIdType blob_i
...
+    write_version(reset_stream, version);
+    reset_stream.flush();
+    reset_stream.close();
+}
+
+[[noreturn]] void rethrow_recoverable_cache_write_failure(std::exception_ptr write_error) {
+    try {
+        std::rethrow_exception(write_error);
+    } catch (const std::filesystem::filesystem_error& ex) {
+        throw std::ios_base::failure(ex.what());
```
Comment (praasz) [inline src/inference/src/single_file_storage.cpp:263]: The std exception should not be used in OV code

File: src/inference/src/single_file_storage.cpp [hunk 16]
```diff
@@ -237,11 +239,82 @@ void SingleFileStorage::write_blob_entry(std::fstream& stream, BlobIdType blob_i
     m_blob_index[blob_id] = {static_cast<uint64_t>(blob_pos), static_cast<uint64_t>(blob_size), std::move(model_name)};
 }
 
+namespace {
+
+void reset_single_file_storage_state(const std::filesystem::path& file_path,
```
Comment (praasz) [inline src/inference/src/single_file_storage.cpp:244]: @t-jankowski 
Could you review it?

File: src/inference/src/single_file_storage.cpp [hunk 17]
```diff
@@ -237,11 +239,82 @@ void SingleFileStorage::write_blob_entry(std::fstream& stream, BlobIdType blob_i
...
+        }
+        std::error_code ec;
+        std::filesystem::resize_file(m_file_path, original_size, ec);
+        if (!ec) {
+            rethrow_recoverable_cache_write_failure(write_error);
+        }
+
+        try {
+            m_blob_index.clear();
+            reset_single_file_storage_state(m_file_path, m_version, m_shared_context);
```
Comment (t-jankowski) [inline src/inference/src/single_file_storage.cpp]: Why the file is first resized and then override to initial state?
If the resize was successful should it remain untouched (in valid state)?

File: src/inference/src/single_file_storage.cpp [hunk 18]
```diff
@@ -237,11 +239,82 @@ void SingleFileStorage::write_blob_entry(std::fstream& stream, BlobIdType blob_i
...
+        } catch (const std::exception& ex) {
+            throw std::filesystem::filesystem_error(
+                "Failed to restore cache file after write failure: " + std::string(ex.what()),
+                m_file_path,
+                std::make_error_code(std::errc::io_error));
+        } catch (...) {
+            throw std::filesystem::filesystem_error("Failed to restore cache file after write failure",
+                                                    m_file_path,
+                                                    std::make_error_code(std::errc::io_error));
+        }
```
Comment (t-jankowski) [inline src/inference/src/single_file_storage.cpp]: It's seem not needed - there shouldn't be any unrecognized exceptions thrown from `try` block.

File: src/inference/tests/unit/single_file_storage.cpp [hunk 19]
```diff
@@ -193,6 +229,71 @@ TEST_F(SingleFileStorageTest, AppendOnlyCacheEntry) {
...
+            stream << "partial";
+            stream.flush();
+        });
+        FAIL() << "Expected std::ios_base::failure";
+    } catch (const std::ios_base::failure&) {
+    } catch (...) {
+        FAIL() << "Unexpected exception type";
+    }
+
+    EXPECT_EQ(test::utils::fileSize(m_file_path.string()), original_size);
```
Comment (t-jankowski) [inline src/inference/tests/unit/single_file_storage.cpp]: What's being tested here??

**Review by t-jankowski — CHANGES_REQUESTED** [review]

**Comment by allnes** [comment]
@praasz @t-jankowski please review again

**Review by praasz — APPROVED** [review]

File: src/inference/src/dev/core_impl.cpp [hunk 20]
```diff
@@ -1546,6 +1546,10 @@ ov::SoPtr<ov::ICompiledModel> ov::CoreImpl::compile_model_and_cache(ov::Plugin&
                                                  header_size_alignment);
                 compiled_model->export_model(stream);
             });
+        } catch (const std::ios_base::failure&) {
+            cache_content.m_cache_manager->remove_cache_entry(cache_content.m_blob_id);
+        } catch (const ov::Exception&) {
+            cache_content.m_cache_manager->remove_cache_entry(cache_content.m_blob_id);
```
Comment (t-jankowski) [inline src/inference/src/dev/core_impl.cpp:1552]: Since warnings aren't recorded here `catch (...)` block is enough

**Review by t-jankowski — APPROVED** [review]
