### PR TITLE
[TF FE] Support Atan2 operation for TensorFlow models

### LINKED ISSUE #20754: [Good First Issue] [TF FE]: Support Atan2 operation for TensorFlow models
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.1/openvino_docs_ops_opset.html).

In order to infer TensorFlow models with [Atan2](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Atan2) operation by OpenVINO, TF FE needs to be extended with this operation support.

### What needs to be done?

For [Atan2](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Atan2) operation support, you need to add the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

Here is an example of loader implementation for TensorFlow `Einsum` operation:

```cpp
OutputVector translate_einsum_op(const NodeContext& node) { 
     auto op_type = node.get_op_type(); 
     TENSORFLOW_OP_VALIDATION(node, op_type == "Einsum", "Internal error: incorrect usage of translate_einsum_op."); 
     auto equation = node.get_attribute<std::string>("equation"); 
  
     OutputVector inputs; 
     for (size_t input_ind = 0; input_ind < node.get_input_size(); ++input_ind) { 
         inputs.push_back(node.get_input(input_ind)); 
     } 
  
     auto einsum = make_shared<Einsum>(inputs, equation); 
     set_node_name(node.get_name(), einsum); 
     return {einsum}; 
 } 
```

In this example, `translate_einsum_op` converts TF `Einsum` into OV `Einsum`. `NodeContext` object passed into the loader packs all info about inputs and attributes of `Einsum` operation. The loader retrieves an attribute of the equation by using the `NodeContext::get_attribute()` method, prepares input vector, creates `Einsum` operation from OV opset and returns a vector of outputs.

Responsibility of a loader is to parse operation attributes, prepare inputs and express TF operation via OV operations sub-graph. Example for `Einsum` demonstrates the resulted sub-graph with one operation. In PR https://github.com/openvinotoolkit/openvino/pull/19007 you can see operation decomposition into multiple node sub-graph.

### Hint

The output range values for `Atan2` is `[-pi; +pi]` different from `Atan`. You need to pay attention to signs of operands `x` and `y`. For more information, read the details in [wiki](https://en.wikipedia.org/wiki/Atan2).

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [OpenVINO TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/README.md)
- [Contribution guide](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers 

### Ticket

TBD

### PR DESCRIPTION
**Pull request by rghvsh**
### Details:
 - *Support Atan2 operation for TensorFlow models*
 - Closes #20754
 

### Tickets:
 - *TBD*

### CODE REVIEW

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+
+using namespace std;
+using namespace ov::opset8;
+
+namespace ov {
+namespace frontend {
+namespace tensorflow {
+namespace op {
+
+OutputVector translate_Atan2_op(const NodeContext& node) {
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:25]:
```suggestion
OutputVector translate_atan2_op(const NodeContext& node) {
```

File: src/frontends/tensorflow/src/op_table.cpp [hunk 2]
```diff
@@ -102,6 +102,7 @@ const std::map<std::string, CreatorFunction> get_supported_ops() {
         // note: BinaryOp translator declaration for each op must to be added in binary_op.cpp file
         {"Add", CreatorFunction(translate_binary_op<opset8::Add>)},
         {"AddV2", CreatorFunction(translate_binary_op<opset8::Add>)},
+        {"Atan2", CreatorFunction(translate_binary_op<opset8::Atan>)},
```
Comment (rkazants) [inline src/frontends/tensorflow/src/op_table.cpp:105]: We don't need template for binary translators since it is not suitable and you implemented individual translator
```suggestion
        {"Atan2", CreatorFunction(translate_atan2_op)},
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 3]
```diff
@@ -0,0 +1,71 @@
+#include "common_op_table.hpp"
+#include "common_op_table.hpp"
+#include "openvino/op/atan.hpp"
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:3]: Please format your code based on clang rules. Your IDE should apply these rules.

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 4]
```diff
@@ -0,0 +1,71 @@
...
+    // handle the fifth condition
+    auto is_x_zero = make_shared<Equal>(x, const_zero);
+    auto is_y_negative = make_shared<Less>(y, const_zero);
+    auto cond4 = make_shared<LogicalAnd>(is_x_zero, is_y_negative);
+    auto const_minus_two = create_same_type_const_scalar<int32_t>(x, -2);
+    auto pi_div_minus_two = make_shared<Divide>(const_pi, const_minus_two);
+    auto result = make_shared<Select>(cond4, pi_div_two, result);
+
+       
+    set_node_name(node.get_name(), result);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:64]: `result` is of `Output<Node>` class. In `set_node_name` you need to pass shared_ptr to `Node` object: `result.get_node_shared_ptr()`.

**Comment by rkazants** [comment]
build_jenkins

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 5]
```diff
@@ -0,0 +1,71 @@
+#include "common_op_table.hpp"
+#include "common_op_table.hpp"
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:2]:
```suggestion
#include "common_op_table.hpp"
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 6]
```diff
@@ -0,0 +1,71 @@
...
+using namespace std;
+using namespace ov::opset8;
+
+namespace ov {
+namespace frontend {
+namespace tensorflow {
+namespace op {
+
+OutputVector translate_atan2_op(const NodeContext& node) {
+    // handle the first condition
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:26]: please explicitly write what is condition in comments, for example,  `x > 0` or `x < 0 && y >=0`

**Comment by rkazants** [comment]
@rghvsh, please fix build issues (https://dev.azure.com/openvinoci/dldt/_build/results?buildId=670616&view=logs&j=b5f22b75-a995-5545-eb44-87d86e78d173&t=d8150bbb-90e5-5a93-fe9d-9aeee1771aec&l=1712):

```
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(17): error C2039: 'opset8': is not a member of 'ov'
C:\a\1\openvino\src\frontends\tensorflow_common\include\common_op_table.hpp(20): note: see declaration of 'ov'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(17): error C2871: 'opset8': a namespace with this name does not exist
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(26): error C2065: 'Divide': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(26): error C2065: 'y': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(26): error C2065: 'x': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(27): error C2065: 'Atan': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(27): error C3536: 'div_y_x': cannot be used before it is initialized
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(27): error C2672: 'std::make_shared': no matching overloaded function found
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(27): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\memory(1590): note: see declaration of 'std::make_shared'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(28): error C2065: 'x': undeclared identifier

```

Also, kindly reminder to inser copyright header:

```
// Copyright (C) 2018-2023 Intel Corporation
// SPDX-License-Identifier: Apache-2.0
//
```

Best regards,
Roman

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+
+using namespace std;
+
+namespace ov {
+namespace frontend {
+namespace tensorflow {
+namespace op {
+
+OutputVector translate_div_no_nan_op(const NodeContext& node) {
+    default_op_checks(node, 2, {"Atan2"});
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:28]: build issue:

```

C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(55): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\memory(1590): note: see declaration of 'std::make_shared'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(56): error C2065: 'LogicalAnd': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(56): error C3536: 'is_x_zero': cannot be used before it is initialized
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(56): error C3536: 'is_y_negative': cannot be used before it is initialized
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(56): error C2672: 'std::make_shared': no matching overloaded function found
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(56): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\memory(1590): note: see declaration of 'std::make_shared'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(58): error C2065: 'Divide': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(58): error C2672: 'make_shared': no matching overloaded function found
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(58): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\memory(1590): note: see declaration of 'std::make_shared'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(59): error C2371: 'result': redefinition; different basic types
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(37): note: see declaration of 'result'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(59): error C2065: 'Select': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(59): error C3536: 'cond3': cannot be used before it is initialized
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(59): error C3536: 'pi_div_two': cannot be used before it is initialized
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(62): error C2371: 'is_x_zero': redefinition; different basic types
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(54): note: see declaration of 'is_x_zero'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(62): error C2065: 'Equal': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(62): error C2672: 'make_shared': no matching overloaded function found
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(62): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\memory(1590): note: see declaration of 'std::make_shared'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(63): error C2371: 'is_y_negative': redefinition; different basic types
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(55): note: see declaration of 'is_y_negative'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(63): error C2065: 'Less': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(63): error C2672: 'make_shared': no matching overloaded function found
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(63): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\memory(1590): note: see declaration of 'std::make_shared'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(64): error C2065: 'LogicalAnd': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(66): error C2065: 'Divide': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(66): error C2672: 'make_shared': no matching overloaded function found
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(66): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\include\memory(1590): note: see declaration of 'std::make_shared'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(67): error C2371: 'result': redefinition; different basic types
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(37): note: see declaration of 'result'
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(67): error C2065: 'Select': undeclared identifier
C:\a\1\openvino\src\frontends\tensorflow_common\src\op\atan2.cpp(67): error C3536: 'cond4': cannot be used before it is initialized
```

**Comment by rkazants** [comment]
Hi @rghvsh,

Build issues still exists, unfortunatelly. See details in CI:
image

Best regards,
Roman

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 8]
```diff
@@ -0,0 +1,75 @@
...
+namespace frontend {
+namespace tensorflow {
+namespace op {
+OutputVector translate_Atan2_op(const NodeContext& node) {
+    default_op_checks(node, 2, {"Atan2"});
+    auto y = node.get_input(0);
+    auto x = node.get_input(1);
+
+    // handle the first condition : x>0
+    auto div_y_x = make_shared<Divide>(y, x);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:32]: you need to add version of operation `v1`: `make_shared<v1::Divide>(y, x)`.
For other operations below please add as well. See documentation to get the version: https://docs.openvino.ai/2023.2/groupov_ops_cpp_api.html

**Comment by rkazants** [comment]
Hi @rghvsh, do you have any update on build issue fixing? Do you have an access to build logs in CI here:
image

**Comment by rghvsh** [comment]
Hey! @rkazants sorry for the delay was not able to work on it for few days, will work on this today.



> Do you have an access to build logs in CI here? image

yes I can see them

**Comment by rkazants** [comment]
> Hey! @rkazants sorry for the delay was not able to work on it for few days, will work on this today.
> 
> > Do you have an access to build logs in CI here? image
> 
> yes I can see them

@rghvsh, excellent. If you don't know to fix some build issue, please ping me. I will try to explain how to fix it.

Best regards,
Roman

**Comment by rghvsh** [comment]
Hey! @rkazants how to fix this issue:
> @azure-pipelines openvino-ngraph-onnx-lin Failing after 10m — Build #20231127.24 failed

Thank You
Raghav

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 9]
```diff
@@ -0,0 +1,77 @@
...
+#include "openvino/op/equal.hpp"
+#include "openvino/op/greater.hpp"
+#include "openvino/op/greater_eq.hpp"
+#include "openvino/op/less.hpp"
+#include "openvino/op/logical_and.hpp"
+#include "openvino/op/multiply.hpp"
+#include "openvino/op/select.hpp"
+#include "openvino/op/subtract.hpp"
+
+
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:20]: you need to add `using namespace ov::op` because operations you use below `make_shared<v1::Less>(y, const_zero);` are from this namespace.

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 10]
```diff
@@ -0,0 +1,78 @@
...
+    auto is_x_positive = make_shared<v1::Greater>(x, const_zero);
+    auto result = make_shared<v1::Select>(is_x_positive, atan, result);
+
+    // handle the second condition : x<0 && y>=0
+    auto const_pi = create_same_type_const_scalar<double>(x, std::atan(1.0) * 4);
+    auto is_x_negative = make_shared<v1::Less>(x, const_zero);
+    auto y_non_negative = make_shared<v1::GreaterEqual>(y, const_zero);
+    auto cond1 = make_shared<v1::LogicalAnd>(is_x_negative, y_non_negative);
+    auto atan_y_x_plus_pi = make_shared<v1::Add>(atan, const_pi);
+    auto result = make_shared<v1::Select>(cond1, atan_y_x_plus_pi, result);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:46]:
```suggestion
    result = make_shared<v1::Select>(cond1, atan_y_x_plus_pi, result);
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 11]
```diff
@@ -0,0 +1,78 @@
...
+
+    // handle the third consition : x<0 && y<0
+    auto is_y_negative = make_shared<v1::Less>(y, const_zero);
+    auto cond2 = make_shared<v1::LogicalAnd>(is_x_negative, is_y_negative);
+    auto atan_y_x_minus_pi = make_shared<v1::Subtract>(atan, const_pi);
+    auto result = make_shared<v1::Select>(cond2, atan_y_x_minus_pi, result);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:52]:
```suggestion
    result = make_shared<v1::Select>(cond2, atan_y_x_minus_pi, result);
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 12]
```diff
@@ -0,0 +1,78 @@
...
+
+    // handle the fourth condition : x=0 && y>0
+    auto is_x_zero = make_shared<v1::Equal>(x, const_zero);
+    auto is_y_positive = make_shared<v1::Greater>(y, const_zero);
+    auto cond3 = make_shared<v1::LogicalAnd>(is_x_zero, is_y_positive);
+    auto const_two = create_same_type_const_scalar<int32_t>(x, 2);
+    auto pi_div_two = make_shared<v1::Divide>(const_pi, const_two);
+    auto result = make_shared<v1::Select>(cond3, pi_div_two, result);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:60]:
```suggestion
    result = make_shared<v1::Select>(cond3, pi_div_two, result);
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 13]
```diff
@@ -0,0 +1,78 @@
...
+
+    // handle the fifth condition : x=0 && y<0
+    auto cond4 = make_shared<v1::LogicalAnd>(is_x_zero, is_y_negative);
+    auto const_minus_two = create_same_type_const_scalar<int32_t>(x, -2);
+    auto pi_div_minus_two = make_shared<v1::Divide>(const_pi, const_minus_two);
+    auto result = make_shared<v1::Select>(cond4, pi_div_two, result);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:66]:
```suggestion
    result = make_shared<v1::Select>(cond4, pi_div_two, result);
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 14]
```diff
@@ -0,0 +1,78 @@
...
+
+    set_node_name(node.get_name(), result);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:68]:
```suggestion
    set_node_name(node.get_name(), result.get_node_shared_ptr());
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 15]
```diff
@@ -0,0 +1,78 @@
...
+    return result->outputs();
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:69]:
```suggestion
    return {result};
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 16]
```diff
@@ -0,0 +1,78 @@
...
+    default_op_checks(node, 2, {"Atan2"});
+    auto y = node.get_input(0);
+    auto x = node.get_input(1);
+
+    // handle the first condition : x>0
+    auto div_y_x = make_shared<v1::Divide>(y, x);
+    auto atan = make_shared<v0::Atan>(div_y_x);
+    auto const_zero = create_same_type_const_scalar<int32_t>(x, 0);
+    auto is_x_positive = make_shared<v1::Greater>(x, const_zero);
+    auto result = make_shared<v1::Select>(is_x_positive, atan, result);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:38]:
```suggestion
    auto result = atan;
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 17]
```diff
@@ -0,0 +1,76 @@
...
+namespace op {
+OutputVector translate_Atan2_op(const NodeContext& node) {
+    default_op_checks(node, 2, {"Atan2"});
+    auto y = node.get_input(0);
+    auto x = node.get_input(1);
+
+    // handle the first condition : x>0
+    auto div_y_x = make_shared<v1::Divide>(y, x);
+    auto atan = make_shared<v0::Atan>(div_y_x);
+    auto result = atan;
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:36]:
```suggestion
    auto const_zero = create_same_type_const_scalar<int32_t>(x, 0);
    auto result = atan;
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 18]
```diff
@@ -0,0 +1,77 @@
...
+OutputVector translate_Atan2_op(const NodeContext& node) {
+    default_op_checks(node, 2, {"Atan2"});
+    auto y = node.get_input(0);
+    auto x = node.get_input(1);
+
+    // handle the first condition : x>0
+    auto div_y_x = make_shared<v1::Divide>(y, x);
+    auto atan = make_shared<v0::Atan>(div_y_x);
+    auto const_zero = create_same_type_const_scalar<int32_t>(x, 0);
+    auto result = atan;
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:37]:
```suggestion
    auto result = atan->output(0);
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 19]
```diff
@@ -0,0 +1,77 @@
+// Copyright (C) 2018-2023 Intel Corporation
+// SPDX-License-Identifier: Apache-2.0
+
+
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:4]:
```suggestion
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 20]
```diff
@@ -0,0 +1,76 @@
...
+#include "openvino/op/equal.hpp"
+#include "openvino/op/greater.hpp"
+#include "openvino/op/greater_eq.hpp"
+#include "openvino/op/less.hpp"
+#include "openvino/op/logical_and.hpp"
+#include "openvino/op/multiply.hpp"
+#include "openvino/op/select.hpp"
+#include "openvino/op/subtract.hpp"
+
+
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:19]:
```suggestion
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 21]
```diff
@@ -0,0 +1,76 @@
...
+    set_node_name(node.get_name(), result.get_node_shared_ptr());
+    return {result};
+}
+
+}  // namespace op
+}  // namespace tensorflow
+}  // namespace frontend
+}  // namespace ov
+
+
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:75]:
```suggestion
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 22]
```diff
@@ -0,0 +1,74 @@
...
+    set_node_name(node.get_name(), result.get_node_shared_ptr());
+    return {result};
+}
+
+}  // namespace op
+}  // namespace tensorflow
+}  // namespace frontend
+}  // namespace ov
+
++
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:74]:
```suggestion
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 23]
```diff
@@ -0,0 +1,74 @@
...
+#include "openvino/op/subtract.hpp"
+
+using namespace std;
+using namespace ov::op;
+
+namespace ov {
+namespace frontend {
+namespace tensorflow {
+namespace op {
+OutputVector translate_Atan2_op(const NodeContext& node) {
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:26]:
```suggestion
namespace op {

OutputVector translate_Atan2_op(const NodeContext& node) {
```

File: src/frontends/tensorflow_common/src/op/atan2.cpp [hunk 24]
```diff
@@ -0,0 +1,73 @@
...
+
+using namespace std;
+using namespace ov::op;
+
+namespace ov {
+namespace frontend {
+namespace tensorflow {
+namespace op {
+
+OutputVector translate_Atan2_op(const NodeContext& node) {
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/atan2.cpp:27]:
```suggestion
OutputVector translate_atan2_op(const NodeContext& node) {
```

**Comment by rghvsh** [comment]
Hey! @rkazants in the build logs it showed that shape should not be int changed it to float last night. The checks/workflow-approval show waiting for status since the last 12 hours is this normal, or should I fix something in the code?

Thank You
Raghav

**Comment by rghvsh** [comment]
Hey! @rkazants 

After the last commit the build logs showed that shape was not supported by int data type fixed that and changed it to float.

In the commit history it shows all test passing but in workflow approval it shows 2 expected checks/workflow waiting approval what should I do?

Thank You
Raghav

File: tests/layer_tests/tensorflow_tests/test_tf_Atan2.py [hunk 25]
```diff
@@ -0,0 +1,46 @@
...
+            x = tf.compat.v1.placeholder(input_type, input_shape, 'x')
+            tf.raw_ops.Atan2(y=y, x=x)
+            tf.compat.v1.global_variables_initializer()
+            tf_net = sess.graph_def
+
+        return tf_net, None
+
+    test_data_basic = [
+        dict(input_shape=[1.0, 1.0], input_type=np.float32),
+        dict(input_shape=[8.0, 8.0], input_type=np.float32),
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Atan2.py:36]:
```suggestion
        dict(input_shape=[1, 2], input_type=np.float32),
        dict(input_shape=[2, 3, 4], input_type=np.float32),
```

File: tests/layer_tests/tensorflow_tests/test_tf_Atan2.py [hunk 26]
```diff
@@ -0,0 +1,46 @@
...
+
+class TestAtan2(CommonTFLayerTest):
+    def _prepare_input(self, inputs_info):
+        assert 'y' in inputs_info
+        assert 'x' in inputs_info
+        y_shape = inputs_info['y']
+        x_shape = inputs_info['x']
+        inputs_data = {}
+        inputs_data['y'] = np.random.rand(*y_shape).astype(self.input_type)
+        inputs_data['x'] = np.random.rand(*x_shape).astype(self.input_type)
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Atan2.py:18]: @rghvsh, here you tests only one case when `x>=0 && y>=0`. Please add test other cases

Comment (rghvsh) [reply tests/layer_tests/tensorflow_tests/test_tf_Atan2.py]: @rkazants I fixed this by adding negative of random.rand with same shape so there will be two cases 
case1: positive is greater or equal , then we get positive
case 2: negative is greater we get negative

Is this method fine?

**Review by rkazants — APPROVED** [review]

**Comment by rkazants** [comment]
build_jenkins

File: tests/layer_tests/tensorflow_tests/test_tf_Atan2.py (hunk 26 above)
Comment (rkazants) [reply tests/layer_tests/tensorflow_tests/test_tf_Atan2.py]: Yes, thanks!

**Comment by rghvsh** [comment]
Thank you @rkazants for helping me through this! My first contribution to a big codebase.

Hoping to make more contributions(and faster) :)

Raghav
