### PR TITLE
[TF FE] Support Conj operation

### LINKED ISSUE #21462: [Good First Issue][TF FE] Support Conj operation for TensorFlow models
### Context

OpenVINO component responsible for support of TensorFlow models is called as TensorFlow Frontend (TF FE). TF FE converts a model represented in [TensorFlow opset](https://www.tensorflow.org/api_docs/python/tf/raw_ops) to a model in [OpenVINO opset](https://docs.openvino.ai/2023.1/openvino_docs_ops_opset.html).

In order to infer TensorFlow models with [Conj](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Conj) operation by OpenVINO, TF FE needs to be extended with this operation support.

### What needs to be done?

For [Conj](https://www.tensorflow.org/api_docs/python/tf/raw_ops/Conj) operation support, you need to add the corresponding loader into TF FE [op](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow_common/src/op) directory and to register it into the dictionary of [Loaders](https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/src/op_table.cpp). One loader is responsible for conversion (or decomposition) of one type of TensorFlow operation.

Here is an example of loader implementation for TensorFlow `Einsum` operation:

```cpp
OutputVector translate_einsum_op(const NodeContext& node) { 
     auto op_type = node.get_op_type(); 
     TENSORFLOW_OP_VALIDATION(node, op_type == "Einsum", "Internal error: incorrect usage of translate_einsum_op."); 
     auto equation = node.get_attribute<std::string>("equation"); 
  
     OutputVector inputs; 
     for (size_t input_ind = 0; input_ind < node.get_input_size(); ++input_ind) { 
         inputs.push_back(node.get_input(input_ind)); 
     } 
  
     auto einsum = make_shared<Einsum>(inputs, equation); 
     set_node_name(node.get_name(), einsum); 
     return {einsum}; 
 } 
```

In this example, `translate_einsum_op` converts TF `Einsum` into OV `Einsum`. `NodeContext` object passed into the loader packs all info about inputs and attributes of `Einsum` operation. The loader retrieves an attribute of the equation by using the `NodeContext::get_attribute()` method, prepares input vector, creates `Einsum` operation from OV opset and returns a vector of outputs.

Responsibility of a loader is to parse operation attributes, prepare inputs and express TF operation via OV operations sub-graph. Example for `Einsum` demonstrates the resulted sub-graph with one operation. In PR https://github.com/openvinotoolkit/openvino/pull/19007 you can see operation decomposition into multiple node sub-graph.

### Hint

OpenVINO does not support directly complex tensors. For supporting this, we use `ComplexTypeMark` that loader for `Conj` should propagate forward by representing complex tensor as floating-point tensor having additional dimension in the tail to contain real and imaginary parts. See examples of support complex tensors by `ComplexAbs` loader from https://github.com/openvinotoolkit/openvino/pull/20860.

### Example Pull Requests

- https://github.com/openvinotoolkit/openvino/pull/20860
- https://github.com/openvinotoolkit/openvino/pull/19007

### Resources

- [Contribution guide - start here!](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [How to Build OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/docs/dev/build.md)
- [Developer documentation for TensorFlow Frontend](https://github.com/openvinotoolkit/openvino/tree/master/src/frontends/tensorflow)
- [What is OpenVINO?](https://github.com/openvinotoolkit/openvino#what-is-openvino-toolkit)
- [Blog post on contributing to OpenVINO](https://github.com/openvinotoolkit/openvino/blob/master/CONTRIBUTING.md)
- [User documentation](https://docs.openvino.ai/)

### Contact points

@openvinotoolkit/openvino-tf-frontend-maintainers

### PR DESCRIPTION
**Pull request by jvr0123**
### Details:
 - *support Conj operation for TF*
 - *Create src/frontends/tensorflow_common/src/op/conj.cpp*
 - *Update src/frontends/tensorflow_common/include/common_op_table.hpp*
 - *Update src/frontsends/tensorflow/src/op_table.cpp*
 - *Created tests/layer_tests/tensorflow_tests/test_tf_Conj.py*

### Tickets:
 - *Closes #21462 ([Support Conj operation for tensorflow models](https://github.com/openvinotoolkit/openvino/issues/21462))*

### CODE REVIEW

File: src/frontends/tensorflow_common/src/op/conj.cpp [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+
+        set_node_name(node.get_name(), conj);
+        auto complex_conj = make_shared<ComplexTypeMark>(conj, complex_part_type);
+        return {complex_conj->output(0)};
+    }
+    
+    set_node_name(node.get_name(), conj);
+    return {conj};
+
+}
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/conj.cpp:49]: please move this logic into `conj_transpose.cpp` or vice versa and create common helper for both translators because I see much duplicate in the code.

**Comment by p-wysocki** [comment]
build_jenkins

**Comment by rkazants** [comment]
Hi @jvr0123, please apply comments

File: src/frontends/tensorflow_common/src/op/conj.cpp (hunk 1 above)
Comment (jvr0123) [reply src/frontends/tensorflow_common/src/op/conj.cpp:49]: > please move this logic into `conj_transpose.cpp` or vice versa and create common helper for both translators because I see much duplicate in the code.

It looks like the operation files don't have headers, I've written a small helper function, but should I then give each class a helper that gets a shared conj ptr? Is there any neat way to create one common helper and call it from each .cpp file?

Comment (rkazants) [reply src/frontends/tensorflow_common/src/op/conj.cpp:49]: Hi @jvr0123, no need to create header file. Please place this common helper in `conj_transpose.cpp` in nameless space and use it by both translators for `Conj` and `ConjTranspose`.

**Comment by rkazants** [comment]
Hi @jvr0123, do you have any update on this task?

Best regards,
Roman

**Comment by jvr0123** [comment]
> Hi @jvr0123, do you have any update on this task?
> 
> Best regards, Roman

Yes, Ive attempted making a helper outside of each namespace but for some strange reason, I am getting a weird build error about the constructor for ov::Shape::Shape{1} not being valid and instead inspecting a '(' token. Can I share the changes?

**Comment by rkazants** [comment]
> , Ive attempted making a helper outside of each namespace but for some strange reason, I am getting a weird build error about the constructor for ov::Shape::Shape{1} not being valid and

Let me elaborate more my proposal. You just need to implement `conj` translator in existing `conj_transpose.cpp`. No need to create any new `.hpp` and `.cpp` file. After that, you find the common logic between `conj` and `conj_transpose` translators and move it to some common helper for both translators. This helper should be placed in nameless namespace.
Please post such update and let us see your error in CI.

Best regards,
Roman

**Comment by rkazants** [comment]
Hi @jvr0123, any update on applying comments.

Best regards,
Roman

**Comment by jvr0123** [comment]
> Hi @jvr0123, any update on applying comments.
> 
> Best regards, Roman

Yes, I've applied the comments and merged what I have into this pull request, but I still get build errors on attempting to call the Shape constructor within make_shared. Do you have any idea why that could be?

File: src/frontends/tensorflow_common/src/op/conj_transpose.cpp [hunk 2]
```diff
@@ -10,6 +10,7 @@
 #include "openvino/op/negative.hpp"
 #include "openvino/op/shape_of.hpp"
 #include "openvino/op/transpose.hpp"
+#include "conj.cpp"
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/conj_transpose.cpp:13]:
```suggestion
```

File: src/frontends/tensorflow_common/src/op/conj.cpp [hunk 3]
```diff
@@ -0,0 +1,56 @@
...
+        auto conj = get_conj_ptr(x);
+
+        set_node_name(node.get_name(), conj);
+        auto complex_conj = make_shared<ComplexTypeMark>(conj, complex_part_type);
+        return {complex_conj->output(0)};
+    }
+
+    set_node_name(node.get_name(), conj);
+    return {conj};
+}
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/conj.cpp:51]: please move this into `conj_transpose.cpp` so you do not need include `.cpp` that is not correct:)

Comment (jvr0123) [reply src/frontends/tensorflow_common/src/op/conj.cpp]: Applied these changes, any idea as to why the shape constructor is failing the make_shared call?

Comment (rkazants) [reply src/frontends/tensorflow_common/src/op/conj.cpp:51]: Please move both `translate_conj_op` and `get_conj_ptr` to `conj_transpose.cpp`. This way we avoid duplication of `get_conj_ptr`

**Comment by rkazants** [comment]
build_jenkins

File: src/frontends/tensorflow_common/src/op/conj_transpose.cpp [hunk 4]
```diff
@@ -14,33 +14,59 @@
 using namespace std;
 using namespace ov::op;
 
+std::shared_ptr<ov::op::v0::Concat> get_conj_ptr(const ov::Output<ov::Node>& node) {
+    auto real_index = make_shared<ov::op::v0::Constant>(ov::element::i32, ov::Shape::Shape{1});
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/conj_transpose.cpp:18]:
```suggestion
    auto real_index = make_shared<ov::op::v0::Constant>(ov::element::i32, ov::Shape{1}, 0);
```

File: src/frontends/tensorflow_common/src/op/conj_transpose.cpp [hunk 5]
```diff
@@ -14,33 +14,59 @@
...
+    auto imag_index = make_shared<v0::Constant>(ov::element::i32, ov::Shape::Shape{1}, 1);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/conj_transpose.cpp:19]:
```suggestion
    auto imag_index = make_shared<v0::Constant>(ov::element::i32, ov::Shape{1}, 1);
```

**Review by rkazants — COMMENTED** [review]
@jvr0123, please check your code. It is not buildable now.

**Comment by jvr0123** [comment]
> @jvr0123, please check your code. It is not buildable now.

This should build now, for whatever reason I thought that the Shape class was wrapped with a Shape namespace

**Review by rkazants — APPROVED** [review]

**Comment by rkazants** [comment]
build_jenkins

**Review by rkazants — COMMENTED** [review]
@jvr0123, please update https://github.com/openvinotoolkit/openvino/blob/master/src/frontends/tensorflow/docs/supported_ops.md documentation that `Conj` gets supported. Without it, CI will fail.

**Comment by rkazants** [comment]
build_jenkins

File: src/frontends/tensorflow/src/op_table.cpp [hunk 6]
```diff
@@ -158,6 +158,7 @@ const std::map<std::string, CreatorFunction> get_supported_ops() {
         {"ClipByValue", CreatorFunction(translate_clip_by_value_op)},
         {"Complex", CreatorFunction(translate_complex_op)},
         {"ComplexAbs", CreatorFunction(translate_complex_abs_op)},
+        {"Conjugate", CreatorFunction(translate_conj_op)},
```
Comment (rkazants) [inline src/frontends/tensorflow/src/op_table.cpp:161]:
```suggestion
        {"Conj", CreatorFunction(translate_conj_op)},
```

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+    ]
+
+    @pytest.mark.parametrize("params", test_data)
+    @pytest.mark.precommit_tf_fe
+    @pytest.mark.nightly
+    def test_conjugate(self, params, ie_device, precision, ir_version, temp_dir,
+                                 use_new_frontend, use_old_api):
+        self._test(*self.create_complex_conjugate_net(**params),
+                   ie_device, precision, ir_version, temp_dir=temp_dir,
+                   use_new_frontend=use_new_frontend, use_old_api=use_old_api)
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py:69]:
```suggestion
    def test_conjugate(self, params, ie_device, precision, ir_version, temp_dir,
                                 use_new_frontend):
        self._test(*self.create_complex_conjugate_net(**params),
                   ie_device, precision, ir_version, temp_dir=temp_dir,
                   use_new_frontend=use_new_frontend)
```

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+    ]
+
+    @pytest.mark.parametrize("params", test_data)
+    @pytest.mark.precommit_tf_fe
+    @pytest.mark.nightly
+    def test_conjugate(self, params, ie_device, precision, ir_version, temp_dir,
+                                 use_new_frontend, use_old_api):
+        self._test(*self.create_conjugate_net(**params),
+                   ie_device, precision, ir_version, temp_dir=temp_dir,
+                   use_new_frontend=use_new_frontend, use_old_api=use_old_api)
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py:119]:
```suggestion
    def test_conjugate(self, params, ie_device, precision, ir_version, temp_dir,
                                 use_new_frontend):
        self._test(*self.create_conjugate_net(**params),
                   ie_device, precision, ir_version, temp_dir=temp_dir,
                   use_new_frontend=use_new_frontend) 
```

**Comment by rkazants** [comment]
@jvr0123, please fix layer tests:

```
install\tests\layer_tests\tensorflow_tests\test_tf_Conj.py:117: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
install\tests\layer_tests\tensorflow_tests\test_tf_Conj.py:96: in create_conjugate_net
    tf.raw_ops.Conj(x=input, perm=perm, name = "Operation")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = ()
kwargs = {'name': 'Operation', 'perm': [0, 2, 1, 3, 4, 5], 'x': <tf.Tensor 'input:0' shape=(1, 2, 3, 4, 5, 6) dtype=float32>}

    def wrapper(*args, **kwargs):
      if args:
        raise TypeError(
            '{f} only takes keyword args (possible keys: {kwargs}). '
            'Please pass these args as kwargs instead.'.format(
                f=f.__name__, kwargs=f_argspec.args
            )
        )
>     return f(**kwargs)
E     TypeError: conj() got an unexpected keyword argument 'x'
```

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+        ref_net = None
+
+        return tf_net, ref_net
+
+    test_data = [
+        (dict(input_shape=[1, 2], perm=[1, 0])),
+        (dict(input_shape=[1, 2, 3], perm=[2, 1, 0])),
+        (dict(input_shape=[1, 2, 3, 4], perm=[0, 3, 2, 1])),
+        (dict(input_shape=[1, 2, 3, 4, 5, 6], perm=[0, 2, 1, 3, 4, 5])),
+    ]
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py:110]: `perm` argument is not needed for `Conj` operation. Also, `Conj` has only `input` and `name` key arguments.

Comment (jvr0123) [reply tests/layer_tests/tensorflow_tests/test_tf_Conj.py:110]: > `perm` argument is not needed for `Conj` operation. Also, `tf.raw_ops.Conj` has only `input` and `name` key arguments.

The arguments still need to be passed as a dict, right?

Comment (rkazants) [reply tests/layer_tests/tensorflow_tests/test_tf_Conj.py:110]: Use `parameterize` fixture in pytest and leave only `input_shape` parameter. `perm` should be removed. Example of `parameterize` fixture you can find here: https://github.com/openvinotoolkit/openvino/blob/master/tests/layer_tests/tensorflow_tests/test_tf_AddTypes.py

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 10]
```diff
@@ -0,0 +1,104 @@
...
+
+        return tf_net, ref_net
+
+
+    @pytest.mark.parametrize("params", [[1,2], [1,2,3], [1,2,3,4], [1,2,3,4,5,6]])
+    @pytest.mark.precommit_tf_fe
+    @pytest.mark.nightly
+    def test_conjugate(self, params, ie_device, precision, ir_version, temp_dir,
+                                 use_new_frontend):
+        self._test(*self.create_complex_conjugate_net(**params),
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py:59]:
```suggestion
    @pytest.mark.parametrize("input_shape", [[1,2], [1,2,3], [1,2,3,4], [1,2,3,4,5,6]])
    @pytest.mark.precommit_tf_fe
    @pytest.mark.nightly
    def test_conjugate(self, input_shape, ie_device, precision, ir_version, temp_dir,
                                 use_new_frontend):
        self._test(*self.create_complex_conjugate_net(input_shape),
```

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 11]
```diff
@@ -0,0 +1,104 @@
...
+        ref_net = None
+
+        return tf_net, ref_net
+
+    @pytest.mark.parametrize("params", [[1,2], [1,2,3], [1,2,3,4], [1,2,3,4,5,6]])
+    @pytest.mark.precommit_tf_fe
+    @pytest.mark.nightly
+    def test_conjugate(self, params, ie_device, precision, ir_version, temp_dir,
+                                 use_new_frontend):
+        self._test(*self.create_conjugate_net(**params),
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py:102]:
```suggestion
    @pytest.mark.parametrize("input_shape", [[1,2], [1,2,3], [1,2,3,4], [1,2,3,4,5,6]])
    @pytest.mark.precommit_tf_fe
    @pytest.mark.nightly
    def test_conjugate(self, input_shape, ie_device, precision, ir_version, temp_dir,
                                 use_new_frontend):
        self._test(*self.create_conjugate_net(input_shape),
```

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 12]
```diff
@@ -0,0 +1,104 @@
...
+            Placeholder->Conjugate    =>       Placeholder->Conjugate
+        """
+
+        tf.compat.v1.reset_default_graph()
+
+        # Create the graph and model
+        with tf.compat.v1.Session() as sess:
+            input = tf.compat.v1.placeholder(np.float32, input_shape, 'input')
+
+            tf.raw_ops.Conj(x=input, name = "Operation")
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py]:
```suggestion
            tf.raw_ops.Conj(input=input, name = "Operation")
```

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 13]
```diff
@@ -0,0 +1,104 @@
...
+        tf.compat.v1.reset_default_graph()
+
+        # Create the graph and model
+        with tf.compat.v1.Session() as sess:
+            real_part = tf.compat.v1.placeholder(np.float32, input_shape, 'real_part')
+            imag_part = tf.compat.v1.placeholder(np.float32, input_shape, 'imag_part')
+
+            complex_input = tf.raw_ops.Complex(real=real_part, imag=imag_part)
+
+            conj= tf.raw_ops.Conj(x=complex_input, name = "Operation")
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py]:
```suggestion
            conj= tf.raw_ops.Conj(input=complex_input, name = "Operation")
```

**Comment by rkazants** [comment]
Hi @jvr0123,

please fix layer test:

```
dtype = tf.float32
attr_def = name: "T"
type: "type"
default_value {
  type: DT_COMPLEX64
}
allowed_values {
  list {
    type: DT_COMPLEX64
    type: DT_COMPLEX128
    type: DT_VARIANT
  }
}

param_name = 'input'

    def _SatisfiesTypeConstraint(dtype, attr_def, param_name):
      if attr_def.HasField("allowed_values"):
        allowed_list = attr_def.allowed_values.list.type
        allowed_values = ", ".join(dtypes.as_dtype(x).name for x in allowed_list)
        if dtype not in allowed_list:
>         raise TypeError(
              f"Value passed to parameter '{param_name}' has DataType "
              f"{dtypes.as_dtype(dtype).name} not in list of allowed values: "
              f"{allowed_values}")
E         TypeError: Value passed to parameter 'input' has DataType float32 not in list of allowed values: complex64, complex128, variant
```

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 14]
```diff
@@ -0,0 +1,104 @@
...
+
+        rng = np.random.default_rng()
+        assert 'real_part' in inputs_info
+        real_part_shape = inputs_info['real_part']
+        assert 'imag_part' in inputs_info
+        imag_part_shape = inputs_info['imag_part']
+
+        inputs_data = {}
+        inputs_data['real_part'] = 4 * rng.random(real_part_shape).astype(np.complex64) - 2
+        inputs_data['imag_part'] = 4 * rng.random(imag_part_shape).astype(np.complex64) - 2
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py:24]: Please revert your latest changes because OV real and imag parts should be floating-point and complex tensors appear after `Complex` operation

File: tests/layer_tests/tensorflow_tests/test_tf_Conj.py [hunk 15]
```diff
@@ -0,0 +1,104 @@
...
+        return tf_net, ref_net
+
+    @pytest.mark.parametrize("input_shape", [[1,2], [1,2,3], [1,2,3,4], [1,2,3,4,5,6]])
+    @pytest.mark.precommit_tf_fe
+    @pytest.mark.nightly
+    def test_conjugate(self, input_shape, ie_device, precision, ir_version, temp_dir,
+                                 use_new_frontend):
+        self._test(*self.create_conjugate_net(input_shape),
+                   ie_device, precision, ir_version, temp_dir=temp_dir,
+                   use_new_frontend=use_new_frontend)
```
Comment (rkazants) [inline tests/layer_tests/tensorflow_tests/test_tf_Conj.py:104]: This one test should be removed because tf.raw_ops.Conj works only for complex input tensor not like `ConjugateTranspose`. See documentation: https://www.tensorflow.org/api_docs/python/tf/raw_ops/Conj
It was a reason of the previous failure.

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
build_jenkins

**Comment by rkazants** [comment]
@jvr0123, please fix layer tests failing:

```
FAILED install\tests\layer_tests\tensorflow_tests\test_tf_Conj.py::TestComplexConjugate::test_conjugate[ ie_device:CPU - precision:FP16 - input_shape:[1, 2, 3] ] - openvino._pyopenvino.OpConversionFailure: Check 'is_conversion_successful' failed at openvino\openvino\src\frontends\tensorflow\src\frontend.cpp:429:
FrontEnd API failed with OpConversionFailure:
[TensorFlow Frontend] Internal error, conversion is failed for Imag operation with a message:
Check 'complex_type_mark' failed at openvino\openvino\src\frontends\tensorflow_common\src\op\real_imag.cpp:36:
FrontEnd API failed with OpValidationFailureWhile validating node 'Imag':
[TensorFlow Frontend] internal error: ComplexTypeMark is not set at the input of Imag

[TensorFlow Frontend] Internal error, conversion is failed for Conj operation with a message:
Check 'find(supported_ops.begin(), supported_ops.end(), op_type) != supported_ops.end()' failed at openvino\openvino\src\frontends\tensorflow_common\src\utils.cpp:270:
FrontEnd API failed with OpValidationFailureWhile validating node 'Conj':
Conj is not supported for conversion.

[TensorFlow Frontend] Internal error, conversion is failed for Real operation with a message:
Check 'complex_type_mark' failed at openvino\openvino\src\frontends\tensorflow_common\src\op\real_imag.cpp:36:
FrontEnd API failed with OpValidationFailureWhile validating node 'Real':
[TensorFlow Frontend] internal error: ComplexTypeMark is not set at the input of Real
```

File: src/frontends/tensorflow_common/src/op/conj_transpose.cpp [hunk 16]
```diff
@@ -14,33 +14,59 @@
...
+
 namespace ov {
 namespace frontend {
 namespace tensorflow {
 namespace op {
 
-OutputVector translate_conj_transpose_op(const NodeContext& node) {
-    default_op_checks(node, 2, {"ConjugateTranspose"}, true);
+OutputVector translate_conj_op(const NodeContext& node) {
+    default_op_checks(node, 1, {"Conjugate"}, true);
```
Comment (rkazants) [inline src/frontends/tensorflow_common/src/op/conj_transpose.cpp:38]:
```suggestion
    default_op_checks(node, 1, {"Conj"}, true);
```

**Comment by rkazants** [comment]
build_jenkins
