### PR TITLE
[GPU] fixing RMS for static layers

### LINKED ISSUE #29017: [Bug]: T5 Text Encoder producing (very) different output on GPU when model is compiled for dynamic vs. static shape
### OpenVINO Version

2025.1 Nightly (openvino_toolkit_windows_2025.1.0.dev20250214_x86_64)

### Operating System

Windows System

### Device used for inference

GPU

### Framework

None

### Model used

T5 Text Encoder

### Issue description

The T5 Text Encoder Model (from Stable Diffusion 3 pipeline) produces very different output when it is compiled & run on GPU using dynamic shapes, vs static shapes. Note that this issue seems to be specific to GPU -- I do not observe the same problem when using CPU.

See reproduce steps below for more details.

### Step-by-step reproduction

I have attached a small C++ reproducer:

[t5_static_vs_dynamic_reproducer.zip](https://github.com/user-attachments/files/18816372/t5_static_vs_dynamic_reproducer.zip)

1. Obtain T5 Text Encoder model by generating SD3 models via the following cmd's. Note: sd3_requirements.txt is packaged with the zip
  ```
  python -m venv my_env
  my_env\Scripts\activate
  pip install --upgrade-strategy eager -r sd3_requirements.txt
  optimum-cli export openvino --model stabilityai/stable-diffusion-3-medium-diffusers --task stable-diffusion --weight-format fp16 stable-diffusion-3-medium-diffusers
  ```

2. Build the small C++ reproducer (cmd.exe shell):
  ```
  call "openvino_toolkit_windows_2025.1.0.dev20250214_x86_64\setupvars.bat"
  mkdir t5_static_vs_dynamic_reproducer-build
  cd t5_static_vs_dynamic_reproducer-build
  cmake ..\t5_static_vs_dynamic_reproducer
  cmake --build . --config Release
  ```

3. Run it.
  ```
  cd Release
  main.exe <path_to>\stable-diffusion-3-medium-diffusers\text_encoder_3\openvino_model.xml GPU
  ```

  You should see the following at the end of the log, which indicates different output between static & dynamic:
  ```
  Mismatch at postiion 0
    static = -0.244141
    dynamic = -0.00371361
  done..
  ```

Note that if you replace 'GPU' with 'CPU', no mismatches are reported.

### Relevant log output

```shell

```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

### PR DESCRIPTION
**Pull request by e-ddykim**
### Details:
 - 'RMS' does not work correctly for static layers when input rank is smaller than 4.
 - closes #29017, #29113

### CODE REVIEW

File: src/plugins/intel_gpu/include/intel_gpu/primitives/rms.hpp [hunk 1]
```diff
@@ -19,16 +19,22 @@ struct rms : public primitive_base<rms> {
...
         : primitive_base(id, {input, gamma}),
-          epsilon(epsilon) {}
+          epsilon(epsilon),
+          input_rank(input_rank) {}
 
     /// @brief Epsilon for not dividing by zero while normalizing
     float epsilon;
 
+    /// @brief The number of dimensions of the input
+    size_t input_rank;
```
Comment (vladimir-paramuzov) [inline src/plugins/intel_gpu/include/intel_gpu/primitives/rms.hpp:36]: What if you just enforce new shape infer for all models with RMS op? will it resolve the issue?

Comment (e-ddykim) [reply src/plugins/intel_gpu/include/intel_gpu/primitives/rms.hpp]: It simply resolved the issue! I updated as you reviewed. Thank you!

**Review by vladimir-paramuzov — APPROVED** [review]
