### PR TITLE
[GPU] Apply enable_large_allocations before ProgramBuilder constant GPU uploads

### LINKED ISSUE #34967: [Bug]: GPU_ENABLE_LARGE_ALLOCATIONS ignored for large constants during GPU compile (ProgramBuilder before program)
### OpenVINO Version

2026.0.0 (repro); fix targets current `master` / post-2026.0 tree.

### Operating System

Other (Please specify in description)

### Device used for inference

GPU

### Framework

PyTorch

### Model used

Minimal synthetic model: PyTorch module with single large `nn.Parameter` and `forward` that adds input slice to parameter slice (see linked comment for full script).

### Issue description

**OS -** WSL2 for Windows

With `GPU_ENABLE_LARGE_ALLOCATIONS` / `ov::intel_gpu::hint::enable_large_allocations` enabled in `compile_model` config, compiling on Intel GPU still fails during compile with `[GPU] Exceeded max size of memory object allocation` when the IR contains a large constant/weight blob. A native OpenVINO opset model with a large constant may behave differently depending on graph structure; the root cause is that the GPU engine’s `enable_large_allocations` flag is applied in `cldnn::program` **after** `ProgramBuilder` already calls `engine.allocate_memory` for `Constant` nodes in `plugin/ops/constant.cpp`. Related: #34856.

### Step-by-step reproduction

1. Install OpenVINO 2026.0.0 (or build from source without the program_builder fix).
2. Run the PyTorch `export_and_compile` script from [issue #34856, comment #4134598858](https://github.com/openvinotoolkit/openvino/issues/34856#issuecomment-4134598858) (large `nn.Parameter`, `convert_model`, `compile_model` with `GPU_ENABLE_LARGE_ALLOCATIONS`).
3. Observe compile failure with max single-allocation assert.

### Relevant log output

```shell
Check '!exceed_allocatable_mem_size' failed at .../ocl_engine.cpp:...
[GPU] Exceeded max size of memory object allocation: requested ... bytes, but max alloc size supported by device is ... bytes.
```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

### PR DESCRIPTION
**Pull request by Sahilbhatane**
### Details:
 - Large `Constant` blobs are uploaded via `engine.allocate_memory()` in `plugin/ops/constant.cpp` while `ProgramBuilder` walks ops, **before** `cldnn::program` is built; the engine’s large-allocation flag was only set in `program` construction, so `compile_model(..., GPU_ENABLE_LARGE_ALLOCATIONS)` could still hit the max single-allocation assert (e.g. PyTorch `convert_model` repro in [#34856](https://github.com/openvinotoolkit/openvino/issues/34856)).
 - Set `m_engine.set_enable_large_allocations(m_config.get_enable_large_allocations())` at the start of the `ProgramBuilder` ctor that takes `model` + `engine` + `config`, with a short comment explaining ordering vs constant creation.

### Tickets:
 - #34967

### AI Assistance:
 - AI assistance used: yes
 - AI was used for issue analysis, tracing the compile path (`ProgramBuilder` vs `program`), and drafting the PR text; the change was applied and committed locally with human review of `program_builder.cpp` and the commit split. Build/tests were not run in this session—CI / a local GPU compile with the [#34856](https://github.com/openvinotoolkit/openvino/issues/34856) repro should be used to validate.

### CODE REVIEW

**Comment by Sahilbhatane** [comment]
This fixes actual issue described in #34856 , were PR #34894 is just a guide to fix the issue this PR will solve the `max allocation issue`

**Comment by Sahilbhatane** [comment]
hey @p-durandin can I get review on this PR as this is a blocking bug for GPU allocations before build.

File: src/plugins/intel_gpu/src/plugin/program_builder.cpp [hunk 1]
```diff
@@ -70,6 +70,8 @@ ProgramBuilder::ProgramBuilder(std::shared_ptr<ov::Model> model, cldnn::engine&
     , m_task_executor(task_executor)
     , m_compilation_context(compilation_context)
     , m_is_inner_program(is_inner_program) {
+    apply_enable_large_allocations_from_config();
```
Comment (Lyamin-Roman) [inline src/plugins/intel_gpu/src/plugin/program_builder.cpp:73]: It seems that it is enough to set this property only in this place
And don't use redundant function
```suggestion
    m_engine.set_enable_large_allocations(m_config.get_enable_large_allocations());
```

**Review by Lyamin-Roman — APPROVED** [review]

**Comment by p-durandin** [comment]
build_jenkins

**Review by p-durandin — APPROVED** [review]
