### PR TITLE
Fix: Defer axis validation in reduce operations to compile/runtime

### LINKED ISSUE #33261: [Bug]: ReduceMean with out-of-range axis raises RuntimeError during node creation (axis validation)
### OpenVINO Version

2025.4.0-20398-7a975177ff4-releases/2025/4

### Operating System

Ubuntu 20.04 (LTS)

### Device used for inference

CPU

### Framework

None

### Model used

A minimal ONNX model (see model.onnx in this folder) that triggers the error. The model contains a Select/Where node whose two data inputs have different types (i64 and i32).

### Issue description

When building an OpenVINO model via Python opset API, creating a ReduceMean node with an out-of-range axis fails immediately during node construction with a RuntimeError coming from axis validation:
Axis 1 out of the tensor rank range [-1, 0].

This is expected behavior for invalid axes, but I’m filing this as a docs/UX improvement request because:
	It may be surprising that the failure happens at node creation time (before core.compile_model()), especially when model-building code is embedded in larger pipelines/fuzzers.
	It would be helpful to document axis validity constraints and/or explicitly state when validation is performed in the Python API docs for reduction ops (ReduceMean / ReduceMax / ReduceMin / etc.).  

### Step-by-step reproduction

import numpy as np
import openvino as ov
from openvino.runtime import Core, Model
from openvino.runtime import opset8 as ops
def build_bad_model():
   
    x = ops.parameter([2], dtype=ov.Type.f32, name="x")

    axes = ops.constant(np.array([1], dtype=np.int64))

    y = ops.reduce_mean(x, axes, keep_dims=False)

    return Model([y], [x], "bad_axis_reduce_mean")

def main():
    print("OpenVINO:", ov.get_version())
    core = Core()
    model = build_bad_model()

    try:
        core.compile_model(model, "CPU")
        print("UNEXPECTED: compiled successfully")
    except Exception as e:
        print("Expected failure:")
        print(type(e).__name__, e)

if __name__ == "__main__":
    main()

### Relevant log output

```shell
warnings.warn(
OpenVINO: 2025.4.0-20398-7a975177ff4-releases/2025/4
Traceback (most recent call last):
  File "/home/nanchang/xw/Rosetta-Fuzzer/lxx.BUG.py", line 33, in <module>
    main()
  File "/home/nanchang/xw/Rosetta-Fuzzer/lxx.BUG.py", line 22, in main
    model = build_bad_model()
  File "/home/nanchang/xw/Rosetta-Fuzzer/lxx.BUG.py", line 15, in build_bad_model
    y = ops.reduce_mean(x, axes, keep_dims=False)
  File "/home/nanchang/anaconda3/envs/polyjuice/lib/python3.10/site-packages/openvino/utils/decorators.py", line 31, in wrapper
    node = node_factory_function(*args, **kwargs)
  File "/home/nanchang/anaconda3/envs/polyjuice/lib/python3.10/site-packages/openvino/opset1/ops.py", line 2410, in reduce_mean
    return _get_node_factory_opset1().create(
  File "/home/nanchang/anaconda3/envs/polyjuice/lib/python3.10/site-packages/openvino/utils/node_factory.py", line 58, in create
    node = self.factory.create(op_type_name, arguments, attributes)
RuntimeError: Check 'is_axis_valid(axis, r)' failed at src/core/src/validation_util.cpp:332:
While validating node 'opset1::ReduceMean ReduceMean_3 (opset1::Parameter x[0]:f32[2], opset1::Constant Constant_2[0]:i64[1]) -> ()' with friendly_name 'ReduceMean_3':
Axis 1 out of the tensor rank range [-1, 0].
```

### Issue submission checklist

- [x] I'm reporting an issue. It's not a question.
- [x] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [x] There is reproducer code and related data files such as images, videos, models, etc.

### PR DESCRIPTION
**Pull request by sshekhar563**
## Summary

This PR addresses issue #33261 by deferring axis validation for reduce operations from node creation time to compile/runtime, improving the user experience when building models with the Python opset API.

## Problem

Previously, when creating reduce operations (ReduceMean, ReduceMax, ReduceMin, etc.) with out-of-range axes via the Python opset API, validation would fail immediately during node construction with a `RuntimeError`. This was surprising behavior since users typically expect validation to occur at `core.compile_model()` time, not during model building.

**Before (problematic behavior):**
```python
import openvino.opset1 as ops
x = ops.parameter([2], name="x")  # 1D tensor
y = ops.reduce_mean(x, axes=[1])  # axis 1 is out of range for rank 1
# RuntimeError: Axis 1 out of the tensor rank range [-1, 0]

**After (improved behavior):**

import openvino.opset1 as ops
x = ops.parameter([2], name="x")  # 1D tensor  
y = ops.reduce_mean(x, axes=[1])  # Node created successfully with dynamic output shape
model = core.compile_model(model, "CPU")  # Validation happens here with clear error message


Fixes #33261

### CODE REVIEW

File: src/core/shape_inference/include/reduce_shape_inference.hpp [hunk 1]
```diff
@@ -59,9 +59,23 @@ std::vector<TRShape> reduce_shape_infer(const util::ReductionBase* op,
     auto axes_val = ov::op::get_input_const_data_as<TRShape, int64_t>(op, 1, tensor_accessor);
 
     if (data_rank.is_static() && axes_val) {
-        ov::util::try_normalize_axes(*axes_val, data_rank, *op);
+        // Check if all axes are valid before normalizing - if not, defer validation to runtime
```
Comment (praasz) [inline src/core/shape_inference/include/reduce_shape_inference.hpp]: This is not correct. 
In OpenVINO if output shape cannot be calculated correctly because of invalid inputs the exception must be thrown.

**Review by praasz — CHANGES_REQUESTED** [review]

File: src/core/shape_inference/include/reduce_shape_inference.hpp (hunk 1 above)
Comment (sshekhar563) [reply src/core/shape_inference/include/reduce_shape_inference.hpp]: "Understood. I attempted to defer the validation to improve the user experience as requested in the issue, but I see now that core shape inference requires strict validation when inputs are known. I will revert this change.
I will instead update the PR to add a documentation warning (docstring) and a unit test to formalize this 'fail-fast' behavior, which addresses the original issue's request for better clarity."

**Comment by sshekhar563** [comment]
@praasz I have reverted the changes to reduce_shape_inference.hpp. Instead, I am converting this PR to a Documentation & Test fix:
Add a unit test (reduce_invalid_axis_out_of_range) to strictly enforce that this validation throws the correct exception.
Updated the Python docstrings to warn users that invalid static axes will raise a RuntimeError at node creation time.

**Comment by praasz** [comment]
> @praasz I have reverted the changes to reduce_shape_inference.hpp. Instead, I am converting this PR to a Documentation & Test fix: Add a unit test (reduce_invalid_axis_out_of_range) to strictly enforce that this validation throws the correct exception. Updated the Python docstrings to warn users that invalid static axes will raise a RuntimeError at node creation time.

The unit test can be added to show there is exception on invalid inputs. 

Docstring update is not required as this is default action for OV nodes.
@p-wysocki could you look at it?

File: src/bindings/python/tests/test_graph/test_reduction.py [hunk 2]
```diff
@@ -160,3 +160,58 @@ def test_reduce_with_keywork():
...
+    """Test that reduction operations with out-of-range axes raise RuntimeError at node creation.
+
+    This test documents the expected 'fail-fast' behavior: when reduction_axes contain
+    constant values that are out of the valid range [-rank, rank-1], a RuntimeError
+    is raised immediately during node creation, not deferred to model compilation.
+
+    This behavior is by design in OpenVINO - shape inference requires strict validation
+    when inputs are known.
+
+    See: https://github.com/openvinotoolkit/openvino/issues/33261
```
Comment (praasz) [inline src/bindings/python/tests/test_graph/test_reduction.py]: Remove there is no to keep it in comments.

**Comment by sshekhar563** [comment]
@praasz Thanks for the review. I've updated the PR to remove the documentation changes, so now it only includes the test case to verify the exception behavior.

**Comment by sshekhar563** [comment]
@praasz Thanks for the review. I’ve removed the comment as suggested and updated the PR accordingly.

**Comment by sshekhar563** [comment]
Hi @praasz , I’ve addressed the requested changes and updated the PR.
Whenever you have time, could you please take another look? Thanks!

**Comment by jgespino** [comment]
@praasz @p-wysocki Could you please review this PR and provide any additional feedback?

File: src/bindings/python/tests/test_graph/test_reduction.py [hunk 3]
```diff
@@ -160,3 +160,42 @@ def test_reduce_with_keywork():
...
+)
+def test_reduce_invalid_axis_raises_immediately(graph_api_helper):
+    shape = [2]  # 1D tensor, rank=1
+    input_data = np.random.randn(*shape).astype(np.float32)
+    invalid_axes = np.array([1])  # axis 1 is out of range for rank 1 (valid: -1, 0)
+
+    with pytest.raises(RuntimeError) as exc_info:
+        graph_api_helper(input_data, invalid_axes)
+
+    assert "out of the tensor rank range" in str(exc_info.value)
```
[the remark this answers is not in the document]
Comment (p-wysocki) [reply src/bindings/python/tests/test_graph/test_reduction.py:183]: The PR goal in the description is outdated.

File: src/bindings/python/tests/test_graph/test_reduction.py [hunk 4]
```diff
@@ -160,3 +160,42 @@ def test_reduce_with_keywork():
...
+)
+def test_reduce_logical_invalid_axis_raises_immediately(graph_api_helper):
+    shape = [2]  # 1D tensor, rank=1
+    input_data = np.random.randn(*shape).astype(bool)
+    invalid_axes = np.array([1])  # axis 1 is out of range for rank 1 (valid: -1, 0)
+
+    with pytest.raises(RuntimeError) as exc_info:
+        graph_api_helper(input_data, invalid_axes)
+
+    assert "out of the tensor rank range" in str(exc_info.value)
```
[the remark this answers is not in the document]
Comment (p-wysocki) [reply src/bindings/python/tests/test_graph/test_reduction.py:201]: PR description is outdated.

**Review by praasz — APPROVED** [review]

**Comment by praasz** [comment]
build_jenkins

**Comment by p-durandin** [comment]
build_jenkins
